// Bundles server/core.ts + the engine into api/_core.mjs (one file, no node_modules needed at runtime).
// Committed so Vercel needs no build-order trickery. `npm test` fails if it is stale: run `npm run bundle:api`.
import {build} from 'esbuild';import {readFileSync,writeFileSync} from 'node:fs';
export async function bundle():Promise<string>{
 const r=await build({entryPoints:['server/core.ts'],bundle:true,platform:'node',format:'esm',target:'node22',write:false,minify:false,banner:{js:'// GENERATED by scripts/bundle-api.ts from server/ and src/. Do not edit.'},legalComments:'none'});
 return r.outputFiles[0].text;}
if(import.meta.url===`file://${process.argv[1]}`){const out=await bundle();writeFileSync('api/_core.mjs',out);console.log(`api/_core.mjs ${out.length} bytes`);}
export const current=()=>readFileSync('api/_core.mjs','utf8');
