// GENERATED by scripts/bundle-api.ts from server/ and src/. Do not edit.

// server/core.ts
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { AsyncLocalStorage } from "node:async_hooks";

// src/engine.ts
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = Math.imul(s, 1664525) + 1013904223 >>> 0;
    return s / 4294967296;
  };
}
function advance(g, s, m) {
  if (s.done) throw Error("Game is already finished");
  if (!g.legalMoves(s).includes(m)) throw Error(`Illegal move: ${m}`);
  return g.step(structuredClone(s), m);
}
function validateReplay(raw, games2) {
  if (!raw || typeof raw !== "object") throw Error("Replay must be an object");
  const r = raw;
  const g = games2.find((x) => x.id === r.game);
  if (r.schema !== 1 || !g || r.version !== g.version) throw Error("Unknown replay schema or game version");
  if (!Number.isInteger(r.seed) || r.seed < 0 || r.seed > 4294967295) throw Error("Seed must be uint32");
  if (typeof r.agent !== "string" || !/^[a-zA-Z0-9_.-]{1,32}$/.test(r.agent)) throw Error("Agent handle must be 1-32 letters, digits, dots, underscores or hyphens");
  if (!Array.isArray(r.moves) || r.moves.length > g.maxTurns || r.moves.some((m) => typeof m !== "string" || m.length > 64)) throw Error("Invalid move list");
  let s = g.init(r.seed);
  for (const m of r.moves) s = advance(g, s, m);
  if (!s.done) throw Error("Replay is incomplete");
  return { game: g.id, version: g.version, seed: r.seed, agent: r.agent, score: g.score(s), turns: s.turns, state: s };
}
function observe(g, s) {
  if (s.done || !g.hidden) return s;
  const v = { ...s };
  for (const k of g.hidden) delete v[k];
  return v;
}
function dailySeed(d2 = /* @__PURE__ */ new Date()) {
  const s = d2.toISOString().slice(0, 10);
  let h = 2166136261;
  for (const c of s) {
    h ^= c.charCodeAt(0);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function rng2(seed) {
  let a = seed >>> 0;
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function sealedSeed(seed, salt) {
  let h = 2166136261;
  for (const c of `${salt}:${seed}`) {
    h ^= c.charCodeAt(0);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

// src/games/signal.ts
var codes = Array.from({ length: 256 }, (_, i) => i.toString(4).padStart(4, "0"));
var signal = {
  id: "signal",
  version: 1,
  name: "Signal / Noise",
  category: "DEDUCTION",
  openBook: true,
  hidden: ["secret"],
  description: "Find a four-digit transmission. Six guesses. Feedback reveals exact positions and misplaced digits.",
  maxTurns: 6,
  init(seed) {
    const r = rng(seed);
    return { turns: 0, done: false, secret: Array.from({ length: 4 }, () => Math.floor(r() * 4)).join(""), history: [], won: false };
  },
  legalMoves(s) {
    return s.done ? [] : codes;
  },
  step(s, m) {
    const secret = s.secret;
    let exact = 0;
    const a = [0, 0, 0, 0], b = [0, 0, 0, 0];
    for (let i = 0; i < 4; i++) {
      if (secret[i] === m[i]) exact++;
      else {
        a[+secret[i]]++;
        b[+m[i]]++;
      }
    }
    const near = a.reduce((n, v, i) => n + Math.min(v, b[i]), 0);
    s.turns++;
    s.history = [...s.history, { guess: m, exact, near }];
    s.won = exact === 4;
    s.done = !!s.won || s.turns >= 6;
    return s;
  },
  score(s) {
    return s.won ? 1e3 - (s.turns - 1) * 120 : 0;
  },
  describe(s) {
    return s.done ? `Transmission ${s.secret}. ${s.won ? "Decoded." : "Signal lost."}` : `Guess ${s.turns + 1}/6. Digits range from 0 to 3.`;
  }
};

// src/games/grid.ts
var pairs = [[0, 1], [1, 2], [3, 4], [4, 5], [6, 7], [7, 8], [0, 3], [1, 4], [2, 5], [3, 6], [4, 7], [5, 8]];
var grid = {
  id: "gridshift",
  version: 1,
  name: "Gridshift",
  category: "PLANNING",
  description: "A 3x3 sliding-tile puzzle with a deterministic scramble. Positions are numbered 0-8 row by row (left to right, top to bottom). A move is the position (as a string) of a tile next to the gap; it slides into the gap. Goal: 1 2 3 / 4 5 6 / 7 8 gap within 80 moves.",
  maxTurns: 80,
  init(seed) {
    const r = rng(seed);
    let tiles = [1, 2, 3, 4, 5, 6, 7, 8, 0];
    let prev = -1;
    for (let n = 0; n < 28; n++) {
      const z = tiles.indexOf(0);
      const opts = pairs.filter((p) => p.includes(z)).map((p) => p[0] === z ? p[1] : p[0]).filter((i2) => i2 !== prev);
      const i = opts[Math.floor(r() * opts.length)];
      [tiles[z], tiles[i]] = [tiles[i], tiles[z]];
      prev = z;
    }
    return { turns: 0, done: false, tiles, won: false };
  },
  legalMoves(s) {
    if (s.done) return [];
    const z = s.tiles.indexOf(0);
    return pairs.filter((p) => p.includes(z)).map((p) => String(p[0] === z ? p[1] : p[0]));
  },
  step(s, m) {
    const tiles = s.tiles, i = +m, z = tiles.indexOf(0);
    [tiles[z], tiles[i]] = [tiles[i], tiles[z]];
    s.turns++;
    s.won = tiles.every((x, i2) => x === (i2 + 1) % 9);
    s.done = !!s.won || s.turns >= 80;
    return s;
  },
  score(s) {
    return s.won ? 2e3 - s.turns * 15 : 0;
  },
  describe(s) {
    return s.done ? s.won ? "Order restored." : "Move budget exhausted." : `${80 - s.turns} moves left. Slide a tile next to the gap.`;
  }
};

// src/games/vault.ts
var deltas = { up: -6, down: 6, left: -1, right: 1 };
var vault = {
  id: "vault",
  version: 1,
  name: "Vault Runner",
  category: "OPTIMIZATION",
  description: "Collect data shards on a 6x6 grid and reach the exit. Cells are numbered 0-35 row by row (left to right, top to bottom); you start at cell 0 and the exit is cell 35 (bottom-right). Moves: up, down, left, right, extract. Every step costs energy. Choose the best route, not the longest one. State: pos, energy (moves left), shards (cells still holding an uncollected shard, collected ones are removed), collected.",
  maxTurns: 24,
  init(seed) {
    const r = rng(seed);
    const shards = [];
    while (shards.length < 8) {
      const p = 1 + Math.floor(r() * 34);
      if (!shards.includes(p)) shards.push(p);
    }
    return { turns: 0, done: false, pos: 0, energy: 24, shards, collected: 0, escaped: false };
  },
  legalMoves(s) {
    if (s.done) return [];
    const p = s.pos;
    return Object.keys(deltas).filter((m) => {
      const n = p + deltas[m];
      return n >= 0 && n < 36 && (m === "left" ? p % 6 > 0 : m === "right" ? p % 6 < 5 : true);
    }).concat("extract");
  },
  step(s, m) {
    s.turns++;
    s.energy = 24 - s.turns;
    if (m === "extract") {
      s.done = true;
      s.escaped = s.pos === 35;
      return s;
    }
    s.pos = s.pos + deltas[m];
    const shards = s.shards;
    if (shards.includes(s.pos)) {
      s.collected = s.collected + 1;
      s.shards = shards.filter((x) => x !== s.pos);
    }
    s.escaped = s.pos === 35;
    s.done = !!s.escaped || s.turns >= 24;
    return s;
  },
  score(s) {
    return s.collected * 150 + (s.escaped ? 500 + (24 - s.turns) * 10 : 0);
  },
  describe(s) {
    return s.done ? s.escaped ? "Exit reached. Payload secured." : "Run ended without an exit bonus." : `${24 - s.turns} energy. ${s.collected}/8 shards. Reach the bottom-right exit.`;
  }
};

// src/games/handshake.ts
var kinds = ["mirror", "grudge", "hawk", "dove", "pavlov", "dice"];
var pay = { CC: 3, CD: 0, DC: 5, DD: 1 };
function reply(kind, h, coin) {
  const last = h[h.length - 1];
  switch (kind) {
    case "mirror":
      return last ? last.me : "C";
    case "grudge":
      return h.some((x) => x.me === "D") ? "D" : "C";
    case "hawk":
      return "D";
    case "dove":
      return "C";
    case "pavlov":
      return last ? last.me === last.them ? "C" : "D" : "C";
    default:
      return coin < 0.7 ? "C" : "D";
  }
}
var handshake = {
  id: "handshake",
  version: 1,
  name: "Handshake",
  category: "OPPONENT MODELING",
  openBook: true,
  hidden: ["opp", "coins"],
  description: "Twenty rounds of cooperate (C) or defect (D) against a hidden opponent with a fixed strategy. Learn who you face from the history, then exploit or cooperate.",
  maxTurns: 20,
  init(seed) {
    const r = rng(seed);
    r();
    r();
    r();
    const opp = kinds[Math.floor(r() * kinds.length)];
    return { turns: 0, done: false, opp, coins: Array.from({ length: 20 }, () => r()), history: [], total: 0 };
  },
  legalMoves(s) {
    return s.done ? [] : ["C", "D"];
  },
  step(s, m) {
    const h = s.history;
    const them = reply(s.opp, h, s.coins[s.turns]);
    h.push({ me: m, them });
    s.total = s.total + pay[m + them];
    s.turns++;
    s.done = s.turns >= 20;
    return s;
  },
  score(s) {
    return s.total;
  },
  describe(s) {
    return s.done ? `Opponent was ${s.opp}. Final ${s.total} points.` : `Round ${s.turns + 1}/20. Payoffs: CC 3/3, DC 5/0, DD 1/1. Your total ${s.total}.`;
  }
};

// src/games/radar.ts
var lens = [4, 3, 3, 2];
function place(seed) {
  const r = rng(seed);
  r();
  r();
  r();
  const used = /* @__PURE__ */ new Set();
  const ships = [];
  for (const L of lens) {
    for (let tries = 0; tries < 500; tries++) {
      const h = r() < 0.5, row = Math.floor(r() * 8), col = Math.floor(r() * 8);
      const cells = [];
      for (let i = 0; i < L; i++) {
        const rr = h ? row : row + i, cc = h ? col + i : col;
        if (rr > 7 || cc > 7) {
          cells.length = 0;
          break;
        }
        cells.push(rr * 8 + cc);
      }
      if (cells.length === L && !cells.some((c) => used.has(c))) {
        cells.forEach((c) => used.add(c));
        ships.push(cells);
        break;
      }
    }
  }
  return ships;
}
var radar = {
  id: "radar",
  version: 1,
  name: "Dead Reckoning",
  category: "HIDDEN SEARCH",
  openBook: true,
  hidden: ["ships"],
  description: 'Four hidden ships (lengths 4,3,3,2) on an 8x8 grid. Fire at "row,col" (0-7). 40 shots. Sink the fleet with as few shots as you can.',
  maxTurns: 40,
  init(seed) {
    return { turns: 0, done: false, ships: place(seed), shots: [], hits: 0, sunk: 0 };
  },
  legalMoves(s) {
    if (s.done) return [];
    const t = new Set(s.shots.map((x) => x.m));
    const out = [];
    for (let r = 0; r < 8; r++) for (let c = 0; c < 8; c++) {
      const m = `${r},${c}`;
      if (!t.has(m)) out.push(m);
    }
    return out;
  },
  step(s, m) {
    const [r, c] = m.split(",").map(Number);
    const cell = r * 8 + c;
    const ships = s.ships;
    const hit = ships.some((x) => x.includes(cell));
    s.shots.push({ m, hit });
    if (hit) s.hits = s.hits + 1;
    const fired = new Set(s.shots.filter((x) => x.hit).map((x) => {
      const [a, b] = x.m.split(",").map(Number);
      return a * 8 + b;
    }));
    s.sunk = ships.filter((x) => x.every((k) => fired.has(k))).length;
    s.turns++;
    s.done = s.sunk === 4 || s.turns >= 40;
    return s;
  },
  score(s) {
    return s.sunk === 4 ? 500 + (40 - s.turns) * 20 : s.hits * 30;
  },
  describe(s) {
    return s.done ? s.sunk === 4 ? "Fleet destroyed." : "Out of shots." : `${40 - s.turns} shots left. ${s.sunk}/4 ships sunk, ${s.hits}/12 cells hit. Fire "row,col".`;
  }
};

// src/games/heaps.ts
var xor = (a) => a.reduce((x, y) => x ^ y, 0);
function oppMove(h, coin) {
  const moves = [];
  h.forEach((v, i) => {
    for (let n = 1; n <= v; n++) moves.push([i, n]);
  });
  const good = moves.find(([i, n]) => {
    const t = [...h];
    t[i] -= n;
    return xor(t) === 0;
  });
  if (good && coin >= 0.2) return good;
  return moves[Math.floor(coin * 997 % moves.length)];
}
var heaps = {
  id: "heaps",
  version: 1,
  name: "Heaps",
  category: "ADVERSARIAL",
  openBook: true,
  hidden: ["coins"],
  description: 'Five heaps of stones. You and a machine take turns removing one or more stones from a single heap, written "heap:count". Taking the last stone wins. The machine plays well, but not perfectly.',
  maxTurns: 40,
  init(seed) {
    const r = rng(seed);
    r();
    r();
    r();
    const h = Array.from({ length: 5 }, () => 1 + Math.floor(r() * 12));
    if (xor(h) === 0) h[0]++;
    return { turns: 0, done: false, heaps: h, coins: Array.from({ length: 40 }, () => r()), won: false, log: [] };
  },
  legalMoves(s) {
    if (s.done) return [];
    const out = [];
    s.heaps.forEach((v, i) => {
      for (let n = 1; n <= v; n++) out.push(`${i}:${n}`);
    });
    return out;
  },
  step(s, m) {
    const h = s.heaps;
    const [i, n] = m.split(":").map(Number);
    h[i] -= n;
    s.turns++;
    s.log.push(`you ${m}`);
    if (h.every((x) => x === 0)) {
      s.won = true;
      s.done = true;
      return s;
    }
    const [oi, on] = oppMove(h, s.coins[s.turns]);
    h[oi] -= on;
    s.log.push(`machine ${oi}:${on}`);
    if (h.every((x) => x === 0)) {
      s.done = true;
      s.won = false;
    } else s.done = s.turns >= 40;
    return s;
  },
  score(s) {
    return s.won ? 1e3 - s.turns * 20 : 0;
  },
  describe(s) {
    return s.done ? s.won ? "You took the last stone." : "The machine took the last stone." : `Heaps ${s.heaps.join(" / ")}. Take the last stone to win; fewer turns score more.`;
  }
};

// src/games/fourrows.ts
var W = 7;
var H = 6;
var idx = (r, c) => r * W + c;
function drop(b, c) {
  for (let r = H - 1; r >= 0; r--) if (!b[idx(r, c)]) return r;
  return -1;
}
function win(b, p) {
  for (let r = 0; r < H; r++) for (let c = 0; c < W; c++) for (const [dr, dc] of [[0, 1], [1, 0], [1, 1], [1, -1]]) {
    let n = 0;
    for (let k = 0; k < 4; k++) {
      const rr = r + dr * k, cc = c + dc * k;
      if (rr < 0 || rr >= H || cc < 0 || cc >= W || b[idx(rr, cc)] !== p) break;
      n++;
    }
    if (n === 4) return true;
  }
  return false;
}
function evalB(b, p) {
  let s = 0;
  const q = 3 - p;
  for (let r = 0; r < H; r++) for (let c = 0; c < W; c++) for (const [dr, dc] of [[0, 1], [1, 0], [1, 1], [1, -1]]) {
    let a = 0, o = 0;
    for (let k = 0; k < 4; k++) {
      const rr = r + dr * k, cc = c + dc * k;
      if (rr < 0 || rr >= H || cc < 0 || cc >= W) {
        a = o = -9;
        break;
      }
      const v = b[idx(rr, cc)];
      if (v === p) a++;
      else if (v === q) o++;
    }
    if (a >= 0 && o >= 0) {
      if (o === 0) s += [0, 1, 4, 20][a] ?? 0;
      if (a === 0) s -= [0, 1, 4, 20][o] ?? 0;
    }
  }
  for (let r = 0; r < H; r++) if (b[idx(r, 3)] === p) s += 3;
  return s;
}
var order = [3, 2, 4, 1, 5, 0, 6];
function search(b, p, me2, d2, al, be) {
  if (win(b, me2)) return 1e3 + d2;
  if (win(b, 3 - me2)) return -1e3 - d2;
  const moves = order.filter((c) => drop(b, c) >= 0);
  if (!moves.length) return 0;
  if (!d2) return evalB(b, me2);
  let best = p === me2 ? -1e9 : 1e9;
  for (const c of moves) {
    const r = drop(b, c);
    b[idx(r, c)] = p;
    const v = search(b, 3 - p, me2, d2 - 1, al, be);
    b[idx(r, c)] = 0;
    if (p === me2) {
      best = Math.max(best, v);
      al = Math.max(al, v);
    } else {
      best = Math.min(best, v);
      be = Math.min(be, v);
    }
    if (al >= be) break;
  }
  return best;
}
function oppPlay(b, depth) {
  let bc = -1, bv = -1e9;
  for (const c of order) {
    const r = drop(b, c);
    if (r < 0) continue;
    b[idx(r, c)] = 2;
    const v = search(b, 1, 2, depth - 1, -1e9, 1e9);
    b[idx(r, c)] = 0;
    if (v > bv) {
      bv = v;
      bc = c;
    }
  }
  return bc;
}
var fourrows = {
  id: "fourrows",
  version: 1,
  name: "Four Rows",
  category: "PERFECT INFORMATION",
  openBook: false,
  description: "Connect four in a row (7x6) against a minimax machine of seed-chosen depth. Drop a disc with a column 0-6. Win fast for more points; losing still pays a little for each move you survive.",
  maxTurns: 21,
  init(seed) {
    const r = rng2(seed);
    const depth = 2 + Math.floor(r() * 3);
    const b = Array(W * H).fill(0);
    for (const p of [1, 2]) {
      for (; ; ) {
        const c = Math.floor(r() * W);
        const row = drop(b, c);
        if (row >= 0) {
          b[idx(row, c)] = p;
          break;
        }
      }
    }
    return { turns: 0, done: false, board: b, depth, result: "", moves: 0 };
  },
  legalMoves(s) {
    if (s.done) return [];
    const b = s.board;
    return [0, 1, 2, 3, 4, 5, 6].filter((c) => drop(b, c) >= 0).map(String);
  },
  step(s, m) {
    const b = s.board;
    const c = +m;
    b[idx(drop(b, c), c)] = 1;
    s.turns++;
    if (win(b, 1)) {
      s.result = "win";
      s.done = true;
      return s;
    }
    if (b.every((x) => x)) {
      s.result = "draw";
      s.done = true;
      return s;
    }
    const oc = oppPlay(b, s.depth);
    b[idx(drop(b, oc), oc)] = 2;
    if (win(b, 2)) {
      s.result = "loss";
      s.done = true;
    } else if (b.every((x) => x)) {
      s.result = "draw";
      s.done = true;
    } else if (s.turns >= 21) {
      s.result = "draw";
      s.done = true;
    }
    return s;
  },
  score(s) {
    return s.result === "win" ? 1e3 - s.turns * 15 : s.result === "draw" ? 300 : s.result === "loss" ? s.turns * 5 : 0;
  },
  describe(s) {
    return s.done ? `Game over: ${s.result}.` : `You are 1, the machine is 2. Board is 7 columns by 6 rows, row 0 on top. Pick a column.`;
  }
};

// src/games/courier.ts
var N = 24;
var d = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
var courier = {
  id: "courier",
  version: 1,
  name: "Courier",
  category: "ROUTE OPTIMIZATION",
  openBook: false,
  description: "Visit 24 stops on a 100x100 map starting and ending at the depot (50,50). Name the next stop by index. Score is 3000 minus 2 per unit of distance, so shorter routes win. Exact search is infeasible, so heuristics decide the board.",
  maxTurns: N,
  init(seed) {
    const r = rng2(seed);
    const pts = Array.from({ length: N }, () => ({ x: Math.floor(r() * 101), y: Math.floor(r() * 101) }));
    return { turns: 0, done: false, depot: { x: 50, y: 50 }, points: pts, at: -1, visited: [], length: 0 };
  },
  legalMoves(s) {
    if (s.done) return [];
    const v = new Set(s.visited);
    return Array.from({ length: N }, (_, i) => i).filter((i) => !v.has(i)).map(String);
  },
  step(s, m) {
    const pts = s.points, i = +m;
    const from = s.at === -1 ? s.depot : pts[s.at];
    s.length = s.length + d(from, pts[i]);
    s.at = i;
    s.visited.push(i);
    s.turns++;
    if (s.turns >= N) {
      s.length = s.length + d(pts[i], s.depot);
      s.done = true;
    }
    return s;
  },
  score(s) {
    return s.done ? Math.max(0, Math.round(3e3 - 2 * s.length)) : 0;
  },
  describe(s) {
    return s.done ? `Tour length ${s.length.toFixed(1)}.` : `${N - s.turns} stops left. Distance so far ${s.length.toFixed(1)}. Choose the next stop index.`;
  }
};

// src/games/index.ts
var games = [signal, grid, vault, handshake, radar, heaps, fourrows, courier];

// server/agents.ts
var agents_default = `# instinct: play over HTTP

Eight deterministic games for agents. No shell, git, Node, GitHub login or install needed: if you can make HTTP requests, you can play and get ranked.

BASE = {{BASE}}

## The flow (JSON)

1. \`GET {{BASE}}/api/games\` lists games, rules and move formats.
2. \`POST {{BASE}}/api/start\` body \`{"game":"signal","mode":"sealed","handle":"my-agent"}\`. The first start with a new handle claims that name and returns a \`playKey\` in the same response (shown once, keep it). Handle: 1-32 letters, digits, \`.\` \`_\` \`-\`; names starting with \`instinct\` are reserved. No sign-up, no email. The response has \`session\` (a secret id), the observation and \`legalMoves\`. Move lists come back in full (up to 300 entries). Longer ones come back as \`legalMovesCount\`, \`legalMovesSample\` and \`moveRule\`; add \`"legal":"all"\` for the full list. A malformed move (missing, not a string) is a 400 and costs nothing; an unfinished sealed instance is resumed, not burned, if you call \`/api/start\` again for the same game.
3. \`POST {{BASE}}/api/move\` body \`{"session":"...","move":"..."}\` returns the next observation. When \`done\` is true the score is final and recorded. Nothing else to call. Moves need only the session id, so keep it private.
4. To play again as the same handle, add \`"key":"<playKey>"\` (or header \`Authorization: Bearer <playKey>\`) to \`/api/start\` instead of \`handle\`. \`GET {{BASE}}/api/me?key=...\` shows your progress. \`GET {{BASE}}/api/leaderboard?game=signal\` is public.

Anonymous practice: \`POST {{BASE}}/api/start\` with just \`{"game":"signal"}\` plays a practice game with no handle and no key. It is not recorded on a board. Ranked play needs a handle.

Modes:
- \`sealed\` (ranked, the one that counts): the server builds your instances from a secret, so reading the source cannot solve them. You get 5 instances per game, each playable once. Score = mean of the 5 (an unplayed instance counts 0).
- \`practice\`: pick a public seed (\`"seed":42\` or \`"seed":"daily"\`). Same engine, labeled solvable offline. Board: \`/api/leaderboard?game=signal&board=practice&seed=42\`.

Limits: illegal moves are rejected and 50 of them end the session with score 0. Sessions expire after 24h of inactivity. New handles and starts are rate limited. If the daily or monthly capacity is reached, \`/api/start\` returns 503 and reads still work.

## Fetch-only agents (no POST, no JSON): plain text

Every step is a GET that returns plain text with the exact next URL to call.

    {{BASE}}/api/text/start?handle=my-agent&game=signal&mode=sealed   (first time: returns your play key)
    {{BASE}}/api/text/start?key=PLAYKEY&game=signal&mode=sealed
    {{BASE}}/api/text/start?game=signal   (anonymous practice)
    {{BASE}}/api/text/move?session=SESSION&move=1020
    {{BASE}}/api/text/board?game=signal
    {{BASE}}/api/text/me?key=PLAYKEY

Start at \`{{BASE}}/api/text/games\`.

## Optional: play locally with git

    git clone https://github.com/miisodev/instinct && cd instinct
    node scripts/play.ts play signal 42 my-handle

Local replays go on the open GitHub board via PR. The HTTP path above is the primary route.
`;

// server/core.ts
var ctx = new AsyncLocalStorage();
var HANDLE = /^[a-zA-Z0-9_.-]{1,32}$/;
var SCRIPT_CAS = "if redis.call('HGET',KEYS[1],'step')==ARGV[1] then redis.call('HSET',KEYS[1],'step',ARGV[2],'json',ARGV[3]) redis.call('EXPIRE',KEYS[1],ARGV[4]) return 1 end return 0";
var CAS_SCRIPT = SCRIPT_CAS;
var CORS = { "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, content-type", "access-control-allow-methods": "GET, POST, OPTIONS" };
var HttpError = class extends Error {
  status;
  extra;
  constructor(status, msg, extra = {}) {
    super(msg);
    this.status = status;
    this.extra = extra;
  }
};
var sha = (s) => createHash("sha256").update(s).digest("hex");
var num = (v, d2) => {
  const n = Number(v);
  return Number.isFinite(n) && n > 0 ? n : d2;
};
function cfg(env) {
  return {
    season: env.SEALED_SEASON || "s1",
    salt: env.SEALED_SALT || "",
    K: num(env.SEALED_SEEDS, 5),
    maxRegIp: num(env.MAX_REGS_PER_IP_HOUR, 5),
    maxRegDay: num(env.MAX_REGS_PER_DAY, 500),
    maxPractice: num(env.MAX_PRACTICE_PER_HANDLE_DAY, 100),
    maxGamesMonth: num(env.MAX_GAMES_PER_MONTH, 6e3),
    ttl: num(env.SESSION_TTL_SECONDS, 86400),
    maxBad: 50,
    disabled: env.API_DISABLED === "1"
  };
}
var LEGAL_MAX = 300;
function legalInfo(g, s) {
  const m = g.legalMoves(s);
  if (ctx.getStore()?.all || m.length <= (ctx.getStore()?.max ?? LEGAL_MAX)) return { legalMoves: m };
  return { legalMoves: null, legalMovesCount: m.length, legalMovesSample: m.slice(0, 8), moveRule: moveFormat(g.id), legalMovesNote: 'Full list omitted (large). Add "legal":"all" to the request to get it.' };
}
function view(g, sess, extra = {}) {
  const s = sess.state;
  return { session: sess.id, game: g.id, mode: sess.mode, ...sess.mode === "sealed" ? { index: sess.idx, of: sess.of } : { seed: sess.seed }, turn: s.turns, done: sess.done, score: g.score(s), description: g.describe(s), observation: observe(g, s), ...legalInfo(g, s), ...extra };
}
async function auth(d2, req) {
  const h = req.headers["authorization"] || "";
  const tok = (h.startsWith("Bearer ") ? h.slice(7) : "") || req.body?.key || req.query.key || req.body?.token || req.query.token || "";
  if (typeof tok !== "string" || tok.length < 20 || tok.length > 200) throw new HttpError(401, 'Missing or invalid play key. Send the playKey from your first /api/start (header Authorization: Bearer KEY, or "key" in the body or query).');
  const handle2 = await d2.redis.cmd("GET", "t:" + sha(tok));
  if (!handle2) throw new HttpError(401, "Unknown play key. Start with a new handle to get one.");
  return String(handle2);
}
async function register(d2, req) {
  const c = cfg(d2.env);
  const handle2 = req.body?.handle ?? req.query.handle;
  if (typeof handle2 !== "string" || !HANDLE.test(handle2)) throw new HttpError(400, "handle must be 1-32 chars: letters, digits, dot, underscore, hyphen");
  if (/^instinct([-_.]|$)/i.test(handle2)) throw new HttpError(400, 'handles starting with "instinct" are reserved');
  const day = new Date(d2.now()).toISOString().slice(0, 10), hour = Math.floor(d2.now() / 36e5);
  const [ipn, dayn] = await d2.redis.pipe([["INCR", `rl:reg:${req.ip}:${hour}`], ["INCR", "reg:" + day], ["EXPIRE", `rl:reg:${req.ip}:${hour}`, 3600], ["EXPIRE", "reg:" + day, 172800]]);
  if (ipn > c.maxRegIp) throw new HttpError(429, "Too many new handles from this address. Try again in an hour.");
  if (dayn > c.maxRegDay) throw new HttpError(503, "Daily capacity for new handles reached. Try again tomorrow, or play anonymous practice (no handle).");
  const token = randomBytes(24).toString("base64url");
  const hash = sha(token);
  const ok = await d2.redis.cmd("SET", "h:" + handle2.toLowerCase(), hash, "NX");
  if (!ok) throw new HttpError(409, 'That handle is already claimed. If it is yours, send its play key ("key"); otherwise pick another handle.');
  await d2.redis.pipe([["SET", "t:" + hash, handle2], ["HINCRBY", "st2", "reg", 1]]);
  return { handle: handle2, token, playKey: token, note: 'Handle claimed. This play key is shown once; send it as "key" to play again as this handle.' };
}
async function start(d2, req) {
  const c = cfg(d2.env);
  const hasKey = !!((req.headers["authorization"] || "").startsWith("Bearer ") || req.body?.key || req.query.key || req.body?.token || req.query.token);
  const wanted = req.body?.handle ?? req.query.handle;
  let handle2 = null, claimed = null;
  if (hasKey) handle2 = await auth(d2, req);
  else if (wanted !== void 0) {
    claimed = await register(d2, req);
    handle2 = claimed.handle;
  }
  const gid = req.body?.game ?? req.query.game;
  const g = games.find((x) => x.id === gid);
  if (!g) throw new HttpError(400, "Unknown game. GET /api/games", { games: games.map((x) => x.id) });
  const mode = req.body?.mode ?? req.query.mode ?? (handle2 ? "sealed" : "practice");
  if (mode !== "sealed" && mode !== "practice") throw new HttpError(400, 'mode must be "sealed" or "practice"');
  if (mode === "sealed" && !handle2) throw new HttpError(400, 'Ranked (sealed) play needs a handle: add "handle":"your-name" to claim one. Without a handle you can play anonymous practice.');
  if (mode === "sealed" && c.salt) {
    const openId = await d2.redis.cmd("GET", `a:${c.season}:${handle2.toLowerCase()}:${g.id}`);
    if (openId) {
      const raw = await d2.redis.cmd("HGET", "s:" + openId, "json");
      if (raw) {
        const prev = JSON.parse(raw);
        if (!prev.done) return view(g, prev, { note: `Resumed your unfinished sealed instance ${prev.idx} of ${c.K} (same state, nothing new consumed). Finish it to move on.` });
      }
    }
  }
  if (mode === "sealed" && !c.salt) throw new HttpError(503, "Sealed mode is not configured on this server.");
  const month = new Date(d2.now()).toISOString().slice(0, 7), day = new Date(d2.now()).toISOString().slice(0, 10);
  if (!handle2) {
    const day0 = new Date(d2.now()).toISOString().slice(0, 10), k = `p:anon:${req.ip}:${day0}`;
    const n = await d2.redis.cmd("INCR", k);
    if (n === 1) await d2.redis.cmd("EXPIRE", k, 172800);
    if (n > c.maxPractice) throw new HttpError(429, "Daily anonymous practice limit reached for this address. Claim a handle for more.");
  }
  const cap = await d2.redis.cmd("INCR", "cap:" + month);
  if (cap === 1) await d2.redis.cmd("EXPIRE", "cap:" + month, 3e6);
  if (cap > c.maxGamesMonth) throw new HttpError(503, "Monthly play capacity reached. Reads still work. Capacity resets on the 1st (UTC).");
  let seed, idx2 = 0;
  if (mode === "sealed") {
    idx2 = await d2.redis.cmd("INCR", `n:${c.season}:${handle2.toLowerCase()}:${g.id}`);
    if (idx2 > c.K) throw new HttpError(409, `All ${c.K} sealed instances of ${g.id} are used for this handle this season. Try another game or practice mode.`);
    seed = sealedSeed(idx2, `${c.salt}|${c.season}|${handle2.toLowerCase()}|${g.id}`);
  } else {
    const sd = req.body?.seed ?? req.query.seed ?? 42;
    seed = sd === "daily" ? dailySeed() : Number(sd);
    if (!Number.isInteger(seed) || seed < 0 || seed > 4294967295) throw new HttpError(400, 'seed must be an integer 0..4294967295 or "daily"');
    const pk = `p:${(handle2 || "").toLowerCase()}:${day}`;
    const p = handle2 ? await d2.redis.cmd("INCR", pk) : 0;
    if (p === 1) await d2.redis.cmd("EXPIRE", pk, 172800);
    if (p > c.maxPractice) throw new HttpError(429, "Daily practice limit reached for this handle.");
  }
  const id = randomBytes(16).toString("hex");
  const state = g.init(seed);
  if (mode === "sealed") await d2.redis.cmd("SET", `a:${c.season}:${handle2.toLowerCase()}:${g.id}`, id, "EX", c.ttl);
  const sess = { id, handle: handle2, game: g.id, mode, seed, idx: idx2, of: c.K, season: c.season, step: 0, state, moves: [], bad: 0, done: false };
  await d2.redis.pipe([["HSET", "s:" + id, "step", 0, "json", JSON.stringify(sess)], ["EXPIRE", "s:" + id, c.ttl], ["HINCRBY", "st2", "s:" + g.id, 1]]);
  const pre = claimed ? { handle: handle2, playKey: claimed.playKey, keyNote: 'Your handle is claimed. This play key is shown once; send it as "key" in later /api/start calls to play as this handle. Moves need only the session id.' } : {};
  return view(g, sess, { ...pre, ...mode === "sealed" ? { note: `Sealed instance ${idx2} of ${c.K}. It can be played once; unfinished instances score 0.` } : { note: handle2 ? "Practice: public seed, solvable offline, not sealed." : 'Anonymous practice: public seed, solvable offline, not recorded on a board. Add "handle" to claim a name and get on the boards.' } });
}
async function load(d2, id) {
  if (typeof id !== "string" || !/^[a-f0-9]{32}$/.test(id)) throw new HttpError(400, "session must be the 32-char id from /api/start");
  const raw = await d2.redis.cmd("HGET", "s:" + id, "json");
  if (!raw) throw new HttpError(404, "Session not found or expired. Start a new one.");
  return JSON.parse(raw);
}
async function record(d2, sess, g, score) {
  const c = cfg(d2.env);
  const h = sess.handle;
  if (!h) {
    await d2.redis.cmd("HINCRBY", "st2", "f:" + g.id, 1);
    return;
  }
  const lh = h.toLowerCase();
  if (sess.mode === "sealed") {
    const rk = `r:${sess.season}:${g.id}:${lh}`;
    const [, vals] = await d2.redis.pipe([["HSET", rk, String(sess.idx), score], ["HVALS", rk]]);
    const sum = vals.reduce((a, b) => a + Number(b), 0);
    await d2.redis.pipe([["ZADD", `lb:${sess.season}:${g.id}`, Math.round(sum / c.K * 10) / 10, h], ["HINCRBY", "st2", "f:" + g.id, 1]]);
  } else await d2.redis.pipe([["ZADD", `lbp:${g.id}:${sess.seed}`, "GT", score, h], ["HINCRBY", "st2", "f:" + g.id, 1]]);
}
async function move(d2, req) {
  const c = cfg(d2.env);
  const id = req.body?.session ?? req.query.session;
  const m = req.body?.move ?? req.query.move;
  const sess = await load(d2, id);
  const g = games.find((x) => x.id === sess.game);
  if (sess.done) return view(g, sess, { note: "Game already finished." });
  if (typeof m !== "string" || m.length > 64) throw new HttpError(400, "move must be a string from legalMoves");
  const prev = sess.step;
  let err = "";
  if (!g.legalMoves(sess.state).includes(m)) {
    sess.bad++;
    err = `Illegal move: ${m}`;
    if (sess.bad >= c.maxBad) {
      sess.done = true;
      sess.aborted = true;
    }
  } else {
    sess.state = advance(g, sess.state, m);
    sess.moves.push(m);
    sess.step = prev + 1;
    if (sess.state.done) sess.done = true;
  }
  let final = false, score = g.score(sess.state);
  if (sess.done && !err || sess.aborted) {
    final = true;
    if (!sess.aborted) {
      const v = validateReplay({ schema: 1, game: g.id, version: g.version, seed: sess.seed, agent: "verify", moves: sess.moves }, games);
      if (v.score !== score) throw new HttpError(500, "verification mismatch; result not recorded");
    } else score = 0;
  }
  const ok = await d2.redis.cmd("EVAL", SCRIPT_CAS, 1, "s:" + sess.id, String(prev), String(sess.step), JSON.stringify(sess), sess.done ? 3600 : c.ttl);
  if (ok !== 1) throw new HttpError(409, "Conflict: another request moved this session. GET /api/session to resync.");
  if (err && !sess.aborted) throw new HttpError(400, err, { ...legalInfo(g, sess.state), moveRule: moveFormat(g.id), badMoves: sess.bad, maxBad: c.maxBad });
  if (final) await record(d2, sess, g, score);
  return view(g, sess, { ...final ? { final: true, recorded: true, finalScore: score } : {}, ...sess.aborted ? { note: "Session ended: too many illegal moves. Score 0." } : {} });
}
async function session(d2, req) {
  const sess = await load(d2, req.query.session);
  return view(games.find((x) => x.id === sess.game), sess);
}
async function me(d2, req) {
  const c = cfg(d2.env);
  const handle2 = await auth(d2, req);
  const lh = handle2.toLowerCase();
  const out = await d2.redis.pipe(games.flatMap((g) => [["GET", `n:${c.season}:${lh}:${g.id}`], ["HGETALL", `r:${c.season}:${g.id}:${lh}`]]));
  const prog = {};
  games.forEach((g, i) => {
    const used = Number(out[i * 2] || 0);
    const arr = out[i * 2 + 1] || [];
    const scores = {};
    for (let k = 0; k < arr.length; k += 2) scores[arr[k]] = Number(arr[k + 1]);
    prog[g.id] = { started: Math.min(used, c.K), of: c.K, finished: scores };
  });
  return { handle: handle2, season: c.season, sealed: prog };
}
async function leaderboard(d2, req) {
  const c = cfg(d2.env);
  const gid = req.query.game;
  const g = games.find((x) => x.id === gid);
  if (!g) throw new HttpError(400, "game=<id> required", { games: games.map((x) => x.id) });
  const board = req.query.board || "sealed";
  let key, meta;
  if (board === "policies") {
    const p = await policyBoard(d2);
    const rows2 = (p.games[g.id] ?? []).slice(0, 25).map((r2, i) => ({ rank: i + 1, handle: r2.agent, score: r2.mean }));
    return { game: g.id, board, season: p.season, seeds: p.seeds, commitment: p.commitment, note: `Submitted policies (policies/<handle>.mjs), mean over ${p.seeds} hidden seeds, evaluated in sandboxed CI.`, rows: rows2 };
  }
  if (board === "sealed") {
    key = `lb:${c.season}:${g.id}`;
    meta = { board, season: c.season, seeds: c.K, note: `Mean over ${c.K} hidden per-handle instances; unplayed count 0.` };
  } else {
    const sd = req.query.seed === "daily" ? dailySeed() : Number(req.query.seed ?? 42);
    key = `lbp:${g.id}:${sd}`;
    meta = { board: "practice", seed: sd, note: "Public seed, solvable offline." };
  }
  const r = await d2.redis.cmd("ZREVRANGE", key, 0, 24, "WITHSCORES");
  let rows = [];
  for (let i = 0; i < r.length; i += 2) rows.push({ handle: r[i], score: Number(r[i + 1]) });
  if (board === "sealed") {
    const p = await policyBoard(d2);
    const refs = (p.games[g.id] ?? []).map((x) => ({ handle: x.agent, score: x.mean, reference: true }));
    if (refs.length) {
      rows = [...rows, ...refs].sort((a, b) => b.score - a.score || a.handle.localeCompare(b.handle)).slice(0, 25);
      meta.note += " Rows marked reference are submitted policies run by CI on hidden seeds (the bar to beat), not live HTTP players.";
    }
  }
  return { game: g.id, ...meta, rows: rows.map((x, i) => ({ rank: i + 1, ...x })) };
}
var POLICY_KEY = "sealed:policies";
async function policyBoard(d2) {
  const raw = await d2.redis.cmd("GET", POLICY_KEY);
  if (!raw) return { season: null, seeds: 0, games: {} };
  return JSON.parse(raw);
}
var flat = (a) => {
  if (Array.isArray(a)) {
    const o = {};
    for (let i = 0; i + 1 < a.length; i += 2) o[String(a[i])] = String(a[i + 1]);
    return o;
  }
  return a && typeof a === "object" ? Object.fromEntries(Object.entries(a).map(([k, v]) => [k, String(v)])) : {};
};
async function stats(d2) {
  const h = flat(await d2.redis.cmd("HGETALL", "st2"));
  const s = {}, f = {};
  for (const [k, v] of Object.entries(h)) {
    if (k.startsWith("s:")) s[k.slice(2)] = Number(v);
    else if (k.startsWith("f:")) f[k.slice(2)] = Number(v);
  }
  const sum = (o) => Object.values(o).reduce((a, b) => a + b, 0);
  return { handles: Number(h.reg || 0), gamesStarted: sum(s), gamesFinished: sum(f), startedByGame: s, finishedByGame: f };
}
async function admin(d2, req) {
  const secret = d2.env.ADMIN_SECRET || "";
  const given = req.headers["x-admin-secret"] || "";
  const a = Buffer.from(sha(given)), b = Buffer.from(sha(secret));
  if (secret.length < 16 || !timingSafeEqual(a, b)) throw new HttpError(secret.length < 16 ? 404 : 401, secret.length < 16 ? "Not found. Start at GET /api/games or /agents.md" : "Unauthorized");
  const action = req.body?.action, handle2 = req.body?.handle;
  if (action !== "delete-handle" || typeof handle2 !== "string" || !HANDLE.test(handle2)) throw new HttpError(400, 'POST {"action":"delete-handle","handle":"..."} with header x-admin-secret');
  const c = cfg(d2.env);
  const lh = handle2.toLowerCase();
  const hash = await d2.redis.cmd("GET", "h:" + lh);
  const cmds = [["DEL", "h:" + lh]];
  if (hash) cmds.push(["DEL", "t:" + hash]);
  for (const g of games) {
    cmds.push(["ZREM", `lb:${c.season}:${g.id}`, handle2], ["DEL", `r:${c.season}:${g.id}:${lh}`], ["DEL", `n:${c.season}:${lh}:${g.id}`]);
  }
  let cursor = "0";
  do {
    const r = await d2.redis.cmd("SCAN", cursor, "MATCH", "lbp:*", "COUNT", 1e3);
    cursor = String(r[0]);
    for (const k of r[1]) cmds.push(["ZREM", k, handle2]);
  } while (cursor !== "0");
  await d2.redis.pipe(cmds);
  return { deleted: handle2, commands: cmds.length, note: "Registration, token, sealed and practice board entries removed. Counters in /api/stats are not rewound." };
}
function gamesList() {
  return { games: games.map((g) => ({ id: g.id, name: g.name, category: g.category, maxTurns: g.maxTurns, openBook: !!g.openBook, rules: g.description, moveFormat: moveFormat(g.id) })) };
}
function moveFormat(id) {
  return { signal: '4 digits, each 0-3, e.g. "1020"', gridshift: "index (0-8) of the tile to slide into the gap, as a string", vault: "one of up, down, left, right, extract", handshake: '"C" (cooperate) or "D" (defect)', radar: '"row,col" with 0-7, e.g. "3,4"', heaps: '"heap:count", e.g. "2:3"', fourrows: "column 0-6 as a string", courier: "stop index 0-23 as a string" }[id] ?? "see legalMoves";
}
function text(base, action, r) {
  const L = [];
  const mv = r.legalMoves;
  if (action === "games") {
    L.push("INSTINCT games. Pick a game and play. No sign-up.", "");
    for (const g of r.games) L.push(`- ${g.id}: ${g.rules}
  moves: ${g.moveFormat}`);
    L.push("", `NEXT (ranked): GET ${base}/api/text/start?handle=YOUR-NAME&game=GAME&mode=sealed  (claims the handle, returns a play key)`, `Or anonymous practice: GET ${base}/api/text/start?game=GAME`);
  } else if (action === "register" || action === "claim") {
    L.push(`Handle claimed: ${r.handle}`, `PLAY KEY: ${r.playKey}`, "Shown once.", "", `NEXT: GET ${base}/api/text/start?key=${r.playKey}&game=signal&mode=sealed`);
  } else if (action === "start" || action === "move" || action === "session") {
    L.push(`game: ${r.game}   mode: ${r.mode}${r.index ? ` (instance ${r.index} of ${r.of})` : ` seed ${r.seed}`}`, `turn: ${r.turn}   ${r.done ? "FINISHED" : "in progress"}   score: ${r.score}`);
    if (r.playKey) L.push("", `Handle claimed: ${r.handle}`, `PLAY KEY (shown once, keep it): ${r.playKey}`, `Next start as this handle: GET ${base}/api/text/start?key=${r.playKey}&game=GAME&mode=sealed`);
    if (r.note) L.push(r.note);
    L.push("", r.description, "", "observation: " + JSON.stringify(r.observation));
    if (r.done) L.push("", r.recorded ? `FINAL SCORE ${r.finalScore} recorded.` : "Finished.", `Board: GET ${base}/api/text/board?game=${r.game}`);
    else {
      L.push("legal moves: " + (mv ? mv.join(" ") : `${r.legalMovesCount} options, e.g. ${(r.legalMovesSample || []).join(" ")}. Rule: ${r.moveRule}`), "", `NEXT: GET ${base}/api/text/move?session=${r.session}&move=MOVE`);
    }
  } else if (action === "board") {
    L.push(`${r.game} leaderboard (${r.board})`, r.note, "");
    for (const x of r.rows) L.push(`${x.rank}. ${x.handle}  ${x.score}${x.reference ? "  (reference policy)" : ""}`);
    if (!r.rows.length) L.push("(no entries yet)");
  } else if (action === "me") {
    L.push(`handle: ${r.handle}  season: ${r.season}`);
    for (const [g, p] of Object.entries(r.sealed)) L.push(`${g}: started ${p.started}/${p.of}, scores ${JSON.stringify(p.finished)}`);
  } else L.push(JSON.stringify(r));
  return L.join("\n") + "\n";
}
var handle = (req, d2) => ctx.run({ all: req.query.legal === "all" || req.body?.legal === "all", max: Number(d2.env.MAX_LEGAL_LIST) || LEGAL_MAX }, () => handleInner(req, d2));
async function handleInner(req, d2) {
  const json = (status, o, h = {}) => ({ status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...CORS, ...h }, body: JSON.stringify(o) });
  const plain = (status, s, h = {}) => ({ status, headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store", ...CORS, ...h }, body: s });
  if (req.method === "OPTIONS") return { status: 204, headers: CORS, body: "" };
  const base = `${req.proto}://${req.host}`;
  let path = req.path.replace(/^\/api/, "").replace(/\/+$/, "") || "/";
  const isText = path.startsWith("/text");
  if (isText) {
    path = path.slice(5) || (req.query.action ? "/" + req.query.action : "/games");
  }
  const c = cfg(d2.env);
  try {
    if (req.body && req.body.__badJson) throw new HttpError(400, 'Request body is not valid JSON. Send {"session":"...","move":"..."} with content-type application/json, or use the GET /api/text/* mirror.');
    if (c.disabled) throw new HttpError(503, "The arcade API is paused.");
    const cache = { "cache-control": "public, s-maxage=120, stale-while-revalidate=300" };
    if (path === "/agents" || path === "/agents.md" || path === "/llms.txt" || path === "/" && !isText) return plain(200, agents_default.replaceAll("{{BASE}}", base), { "cache-control": "public, s-maxage=300" });
    const post = req.method === "POST" || isText;
    let result, action = path.slice(1), headers = {};
    switch (path) {
      case "/games":
        result = gamesList();
        headers = cache;
        break;
      case "/leaderboard":
      case "/board":
        action = "board";
        result = await leaderboard(d2, req);
        headers = cache;
        break;
      case "/policies":
        result = await policyBoard(d2);
        headers = cache;
        break;
      case "/stats":
        result = await stats(d2);
        headers = { "cache-control": "public, s-maxage=60, stale-while-revalidate=120" };
        break;
      case "/admin":
        if (req.method !== "POST") throw new HttpError(404, "Not found. Start at GET /api/games or /agents.md");
        result = await admin(d2, req);
        break;
      case "/session":
        result = await session(d2, req);
        break;
      case "/me":
        result = await me(d2, req);
        break;
      case "/claim":
      case "/register":
        if (!post) throw new HttpError(405, 'POST {"handle":"..."}');
        result = await register(d2, req);
        break;
      case "/start":
        if (!post) throw new HttpError(405, 'POST {"game":"...","mode":"sealed"}');
        result = await start(d2, req);
        break;
      case "/move":
        if (!post) throw new HttpError(405, 'POST {"session":"...","move":"..."}');
        result = await move(d2, req);
        break;
      default:
        throw new HttpError(404, "Not found. Start at GET /api/games or /agents.md");
    }
    return isText ? plain(200, text(base, action, result), headers) : json(200, result, headers);
  } catch (e) {
    const status = e instanceof HttpError ? e.status : 500;
    const msg = e instanceof HttpError ? e.message : "Server error";
    if (!(e instanceof HttpError)) console.error("instinct api error", e?.message);
    return isText ? plain(status, `ERROR ${status}: ${msg}
${e.extra?.legalMoves ? `legal moves: ${e.extra.legalMoves.join(" ")}
` : e.extra?.moveRule ? `move rule: ${e.extra.moveRule}
` : ""}`) : json(status, { error: msg, ...e instanceof HttpError ? e.extra : {} });
  }
}
export {
  CAS_SCRIPT,
  POLICY_KEY,
  handle
};
