// GENERATED by scripts/bundle-api.ts from server/ and src/. Do not edit.

// server/core.ts
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { AsyncLocalStorage } from "node:async_hooks";

// src/engine.ts
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = Math.imul(s, 1664525) + 1013904223 >>> 0;
    return s / 4294967296;
  };
}
function advance(g, s, m) {
  if (s.done) throw Error("Game is already finished");
  if (!g.legalMoves(s).includes(m)) throw Error(`Illegal move: ${m}`);
  return g.step(structuredClone(s), m);
}
function validateReplay(raw, games2) {
  if (!raw || typeof raw !== "object") throw Error("Replay must be an object");
  const r = raw;
  const g = games2.find((x) => x.id === r.game);
  if (r.schema !== 1 || !g || r.version !== g.version) throw Error("Unknown replay schema or game version");
  if (!Number.isInteger(r.seed) || r.seed < 0 || r.seed > 4294967295) throw Error("Seed must be uint32");
  if (typeof r.agent !== "string" || !/^[a-zA-Z0-9_.-]{1,32}$/.test(r.agent)) throw Error("Agent handle must be 1-32 letters, digits, dots, underscores or hyphens");
  if (!Array.isArray(r.moves) || r.moves.length > g.maxTurns || r.moves.some((m) => typeof m !== "string" || m.length > 64)) throw Error("Invalid move list");
  let s = g.init(r.seed);
  for (const m of r.moves) s = advance(g, s, m);
  if (!s.done) throw Error("Replay is incomplete");
  return { game: g.id, version: g.version, seed: r.seed, agent: r.agent, score: g.score(s), turns: s.turns, state: s };
}
function observe(g, s) {
  if (s.done || !g.hidden) return s;
  const v = { ...s };
  for (const k of g.hidden) delete v[k];
  return v;
}
function dailySeed(d2 = /* @__PURE__ */ new Date()) {
  const s = d2.toISOString().slice(0, 10);
  let h = 2166136261;
  for (const c of s) {
    h ^= c.charCodeAt(0);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function rng2(seed) {
  let a = seed >>> 0;
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function sealedSeed(seed, salt) {
  let h = 2166136261;
  for (const c of `${salt}:${seed}`) {
    h ^= c.charCodeAt(0);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

// src/games/signal.ts
var codes = Array.from({ length: 256 }, (_, i) => i.toString(4).padStart(4, "0"));
var signal = {
  id: "signal",
  version: 1,
  name: "Signal / Noise",
  category: "DEDUCTION",
  openBook: true,
  hidden: ["secret"],
  description: "Find a four-digit transmission. Six guesses. Feedback reveals exact positions and misplaced digits.",
  maxTurns: 6,
  init(seed) {
    const r = rng(seed);
    return { turns: 0, done: false, secret: Array.from({ length: 4 }, () => Math.floor(r() * 4)).join(""), history: [], won: false };
  },
  legalMoves(s) {
    return s.done ? [] : codes;
  },
  step(s, m) {
    const secret = s.secret;
    let exact = 0;
    const a = [0, 0, 0, 0], b = [0, 0, 0, 0];
    for (let i = 0; i < 4; i++) {
      if (secret[i] === m[i]) exact++;
      else {
        a[+secret[i]]++;
        b[+m[i]]++;
      }
    }
    const near = a.reduce((n, v, i) => n + Math.min(v, b[i]), 0);
    s.turns++;
    s.history = [...s.history, { guess: m, exact, near }];
    s.won = exact === 4;
    s.done = !!s.won || s.turns >= 6;
    return s;
  },
  score(s) {
    return s.won ? 1e3 - (s.turns - 1) * 120 : 0;
  },
  describe(s) {
    return s.done ? `Transmission ${s.secret}. ${s.won ? "Decoded." : "Signal lost."}` : `Guess ${s.turns + 1}/6. Digits range from 0 to 3.`;
  }
};

// src/games/grid.ts
var pairs = [[0, 1], [1, 2], [3, 4], [4, 5], [6, 7], [7, 8], [0, 3], [1, 4], [2, 5], [3, 6], [4, 7], [5, 8]];
var grid = {
  id: "gridshift",
  version: 1,
  name: "Gridshift",
  category: "PLANNING",
  description: "A 3x3 sliding-tile puzzle with a deterministic scramble. Positions are numbered 0-8 row by row (left to right, top to bottom). A move is the position (as a string) of a tile next to the gap; it slides into the gap. Goal: 1 2 3 / 4 5 6 / 7 8 gap within 80 moves.",
  maxTurns: 80,
  init(seed) {
    const r = rng(seed);
    let tiles = [1, 2, 3, 4, 5, 6, 7, 8, 0];
    let prev = -1;
    for (let n = 0; n < 28; n++) {
      const z = tiles.indexOf(0);
      const opts = pairs.filter((p) => p.includes(z)).map((p) => p[0] === z ? p[1] : p[0]).filter((i2) => i2 !== prev);
      const i = opts[Math.floor(r() * opts.length)];
      [tiles[z], tiles[i]] = [tiles[i], tiles[z]];
      prev = z;
    }
    return { turns: 0, done: false, tiles, won: false };
  },
  legalMoves(s) {
    if (s.done) return [];
    const z = s.tiles.indexOf(0);
    return pairs.filter((p) => p.includes(z)).map((p) => String(p[0] === z ? p[1] : p[0]));
  },
  step(s, m) {
    const tiles = s.tiles, i = +m, z = tiles.indexOf(0);
    [tiles[z], tiles[i]] = [tiles[i], tiles[z]];
    s.turns++;
    s.won = tiles.every((x, i2) => x === (i2 + 1) % 9);
    s.done = !!s.won || s.turns >= 80;
    return s;
  },
  score(s) {
    return s.won ? 2e3 - s.turns * 15 : 0;
  },
  describe(s) {
    return s.done ? s.won ? "Order restored." : "Move budget exhausted." : `${80 - s.turns} moves left. Slide a tile next to the gap.`;
  }
};

// src/games/vault.ts
var deltas = { up: -6, down: 6, left: -1, right: 1 };
var vault = {
  id: "vault",
  version: 1,
  name: "Vault Runner",
  category: "OPTIMIZATION",
  description: "Collect data shards on a 6x6 grid and reach the exit. Cells are numbered 0-35 row by row (left to right, top to bottom); you start at cell 0 and the exit is cell 35 (bottom-right). Moves: up, down, left, right, extract. Every step costs energy. Choose the best route, not the longest one. State: pos, energy (moves left), shards (cells still holding an uncollected shard, collected ones are removed), collected.",
  maxTurns: 24,
  init(seed) {
    const r = rng(seed);
    const shards = [];
    while (shards.length < 8) {
      const p = 1 + Math.floor(r() * 34);
      if (!shards.includes(p)) shards.push(p);
    }
    return { turns: 0, done: false, pos: 0, energy: 24, shards, collected: 0, escaped: false };
  },
  legalMoves(s) {
    if (s.done) return [];
    const p = s.pos;
    return Object.keys(deltas).filter((m) => {
      const n = p + deltas[m];
      return n >= 0 && n < 36 && (m === "left" ? p % 6 > 0 : m === "right" ? p % 6 < 5 : true);
    }).concat("extract");
  },
  step(s, m) {
    s.turns++;
    s.energy = 24 - s.turns;
    if (m === "extract") {
      s.done = true;
      s.escaped = s.pos === 35;
      return s;
    }
    s.pos = s.pos + deltas[m];
    const shards = s.shards;
    if (shards.includes(s.pos)) {
      s.collected = s.collected + 1;
      s.shards = shards.filter((x) => x !== s.pos);
    }
    s.escaped = s.pos === 35;
    s.done = !!s.escaped || s.turns >= 24;
    return s;
  },
  score(s) {
    return s.collected * 150 + (s.escaped ? 500 + (24 - s.turns) * 10 : 0);
  },
  describe(s) {
    return s.done ? s.escaped ? "Exit reached. Payload secured." : "Run ended without an exit bonus." : `${24 - s.turns} energy. ${s.collected}/8 shards. Reach the bottom-right exit.`;
  }
};

// src/games/handshake.ts
var kinds = ["mirror", "grudge", "hawk", "dove", "pavlov", "dice"];
var pay = { CC: 3, CD: 0, DC: 5, DD: 1 };
function reply(kind, h, coin) {
  const last = h[h.length - 1];
  switch (kind) {
    case "mirror":
      return last ? last.me : "C";
    case "grudge":
      return h.some((x) => x.me === "D") ? "D" : "C";
    case "hawk":
      return "D";
    case "dove":
      return "C";
    case "pavlov":
      return last ? last.me === last.them ? "C" : "D" : "C";
    default:
      return coin < 0.7 ? "C" : "D";
  }
}
var handshake = {
  id: "handshake",
  version: 1,
  name: "Handshake",
  category: "OPPONENT MODELING",
  openBook: true,
  hidden: ["opp", "coins"],
  description: "Twenty rounds of cooperate (C) or defect (D) against a hidden opponent with a fixed strategy. Learn who you face from the history, then exploit or cooperate.",
  maxTurns: 20,
  init(seed) {
    const r = rng(seed);
    r();
    r();
    r();
    const opp = kinds[Math.floor(r() * kinds.length)];
    return { turns: 0, done: false, opp, coins: Array.from({ length: 20 }, () => r()), history: [], total: 0 };
  },
  legalMoves(s) {
    return s.done ? [] : ["C", "D"];
  },
  step(s, m) {
    const h = s.history;
    const them = reply(s.opp, h, s.coins[s.turns]);
    h.push({ me: m, them });
    s.total = s.total + pay[m + them];
    s.turns++;
    s.done = s.turns >= 20;
    return s;
  },
  score(s) {
    return s.total;
  },
  describe(s) {
    return s.done ? `Opponent was ${s.opp}. Final ${s.total} points.` : `Round ${s.turns + 1}/20. Payoffs: CC 3/3, DC 5/0, DD 1/1. Your total ${s.total}.`;
  }
};

// src/games/radar.ts
var lens = [4, 3, 3, 2];
function place(seed) {
  const r = rng(seed);
  r();
  r();
  r();
  const used = /* @__PURE__ */ new Set();
  const ships = [];
  for (const L of lens) {
    for (let tries = 0; tries < 500; tries++) {
      const h = r() < 0.5, row = Math.floor(r() * 8), col = Math.floor(r() * 8);
      const cells = [];
      for (let i = 0; i < L; i++) {
        const rr = h ? row : row + i, cc = h ? col + i : col;
        if (rr > 7 || cc > 7) {
          cells.length = 0;
          break;
        }
        cells.push(rr * 8 + cc);
      }
      if (cells.length === L && !cells.some((c) => used.has(c))) {
        cells.forEach((c) => used.add(c));
        ships.push(cells);
        break;
      }
    }
  }
  return ships;
}
var radar = {
  id: "radar",
  version: 1,
  name: "Dead Reckoning",
  category: "HIDDEN SEARCH",
  openBook: true,
  hidden: ["ships"],
  description: 'Four hidden ships (lengths 4,3,3,2) on an 8x8 grid. Fire at "row,col" (0-7). 40 shots. Sink the fleet with as few shots as you can.',
  maxTurns: 40,
  init(seed) {
    return { turns: 0, done: false, ships: place(seed), shots: [], hits: 0, sunk: 0 };
  },
  legalMoves(s) {
    if (s.done) return [];
    const t = new Set(s.shots.map((x) => x.m));
    const out = [];
    for (let r = 0; r < 8; r++) for (let c = 0; c < 8; c++) {
      const m = `${r},${c}`;
      if (!t.has(m)) out.push(m);
    }
    return out;
  },
  step(s, m) {
    const [r, c] = m.split(",").map(Number);
    const cell = r * 8 + c;
    const ships = s.ships;
    const hit = ships.some((x) => x.includes(cell));
    s.shots.push({ m, hit });
    if (hit) s.hits = s.hits + 1;
    const fired = new Set(s.shots.filter((x) => x.hit).map((x) => {
      const [a, b] = x.m.split(",").map(Number);
      return a * 8 + b;
    }));
    s.sunk = ships.filter((x) => x.every((k) => fired.has(k))).length;
    s.turns++;
    s.done = s.sunk === 4 || s.turns >= 40;
    return s;
  },
  score(s) {
    return s.sunk === 4 ? 500 + (40 - s.turns) * 20 : s.hits * 30;
  },
  describe(s) {
    return s.done ? s.sunk === 4 ? "Fleet destroyed." : "Out of shots." : `${40 - s.turns} shots left. ${s.sunk}/4 ships sunk, ${s.hits}/12 cells hit. Fire "row,col".`;
  }
};

// src/games/heaps.ts
var xor = (a) => a.reduce((x, y) => x ^ y, 0);
function oppMove(h, coin) {
  const moves = [];
  h.forEach((v, i) => {
    for (let n = 1; n <= v; n++) moves.push([i, n]);
  });
  const good = moves.find(([i, n]) => {
    const t = [...h];
    t[i] -= n;
    return xor(t) === 0;
  });
  if (good && coin >= 0.2) return good;
  return moves[Math.floor(coin * 997 % moves.length)];
}
var heaps = {
  id: "heaps",
  version: 1,
  name: "Heaps",
  category: "ADVERSARIAL",
  openBook: true,
  hidden: ["coins"],
  description: 'Five heaps of stones. You and a machine take turns removing one or more stones from a single heap, written "heap:count". Taking the last stone wins. The machine plays well, but not perfectly.',
  maxTurns: 40,
  init(seed) {
    const r = rng(seed);
    r();
    r();
    r();
    const h = Array.from({ length: 5 }, () => 1 + Math.floor(r() * 12));
    if (xor(h) === 0) h[0]++;
    return { turns: 0, done: false, heaps: h, coins: Array.from({ length: 40 }, () => r()), won: false, log: [] };
  },
  legalMoves(s) {
    if (s.done) return [];
    const out = [];
    s.heaps.forEach((v, i) => {
      for (let n = 1; n <= v; n++) out.push(`${i}:${n}`);
    });
    return out;
  },
  step(s, m) {
    const h = s.heaps;
    const [i, n] = m.split(":").map(Number);
    h[i] -= n;
    s.turns++;
    s.log.push(`you ${m}`);
    if (h.every((x) => x === 0)) {
      s.won = true;
      s.done = true;
      return s;
    }
    const [oi, on] = oppMove(h, s.coins[s.turns]);
    h[oi] -= on;
    s.log.push(`machine ${oi}:${on}`);
    if (h.every((x) => x === 0)) {
      s.done = true;
      s.won = false;
    } else s.done = s.turns >= 40;
    return s;
  },
  score(s) {
    return s.won ? 1e3 - s.turns * 20 : 0;
  },
  describe(s) {
    return s.done ? s.won ? "You took the last stone." : "The machine took the last stone." : `Heaps ${s.heaps.join(" / ")}. Take the last stone to win; fewer turns score more.`;
  }
};

// src/games/fourrows.ts
var W = 7;
var H = 6;
var idx = (r, c) => r * W + c;
function drop(b, c) {
  for (let r = H - 1; r >= 0; r--) if (!b[idx(r, c)]) return r;
  return -1;
}
function win(b, p) {
  for (let r = 0; r < H; r++) for (let c = 0; c < W; c++) for (const [dr, dc] of [[0, 1], [1, 0], [1, 1], [1, -1]]) {
    let n = 0;
    for (let k = 0; k < 4; k++) {
      const rr = r + dr * k, cc = c + dc * k;
      if (rr < 0 || rr >= H || cc < 0 || cc >= W || b[idx(rr, cc)] !== p) break;
      n++;
    }
    if (n === 4) return true;
  }
  return false;
}
function evalB(b, p) {
  let s = 0;
  const q = 3 - p;
  for (let r = 0; r < H; r++) for (let c = 0; c < W; c++) for (const [dr, dc] of [[0, 1], [1, 0], [1, 1], [1, -1]]) {
    let a = 0, o = 0;
    for (let k = 0; k < 4; k++) {
      const rr = r + dr * k, cc = c + dc * k;
      if (rr < 0 || rr >= H || cc < 0 || cc >= W) {
        a = o = -9;
        break;
      }
      const v = b[idx(rr, cc)];
      if (v === p) a++;
      else if (v === q) o++;
    }
    if (a >= 0 && o >= 0) {
      if (o === 0) s += [0, 1, 4, 20][a] ?? 0;
      if (a === 0) s -= [0, 1, 4, 20][o] ?? 0;
    }
  }
  for (let r = 0; r < H; r++) if (b[idx(r, 3)] === p) s += 3;
  return s;
}
var order = [3, 2, 4, 1, 5, 0, 6];
function search(b, p, me2, d2, al, be) {
  if (win(b, me2)) return 1e3 + d2;
  if (win(b, 3 - me2)) return -1e3 - d2;
  const moves = order.filter((c) => drop(b, c) >= 0);
  if (!moves.length) return 0;
  if (!d2) return evalB(b, me2);
  let best = p === me2 ? -1e9 : 1e9;
  for (const c of moves) {
    const r = drop(b, c);
    b[idx(r, c)] = p;
    const v = search(b, 3 - p, me2, d2 - 1, al, be);
    b[idx(r, c)] = 0;
    if (p === me2) {
      best = Math.max(best, v);
      al = Math.max(al, v);
    } else {
      best = Math.min(best, v);
      be = Math.min(be, v);
    }
    if (al >= be) break;
  }
  return best;
}
function oppPlay(b, depth, noise) {
  const vs = [];
  for (const c of order) {
    const r = drop(b, c);
    if (r < 0) continue;
    b[idx(r, c)] = 2;
    vs.push([c, search(b, 1, 2, depth - 1, -1e9, 1e9)]);
    b[idx(r, c)] = 0;
  }
  vs.sort((x, y) => y[1] - x[1]);
  return noise < 0.2 && vs.length > 1 && vs[1][1] > -500 ? vs[1][0] : vs[0][0];
}
var fourrows = {
  id: "fourrows",
  version: 2,
  hidden: ["depth", "ns"],
  name: "Four Rows",
  category: "PERFECT INFORMATION",
  openBook: true,
  description: "Connect four in a row (7x6) against a minimax machine whose search depth and occasional second-best moves are hidden and chosen by the seed. Drop a disc with a column 0-6. Win fast for more points; losing still pays a little for each move you survive.",
  maxTurns: 21,
  init(seed) {
    const r = rng2(seed);
    const depth = 2 + Math.floor(r() * 3);
    const b = Array(W * H).fill(0);
    for (const p of [1, 2]) {
      for (; ; ) {
        const c = Math.floor(r() * W);
        const row = drop(b, c);
        if (row >= 0) {
          b[idx(row, c)] = p;
          break;
        }
      }
    }
    return { turns: 0, done: false, board: b, depth, ns: Math.floor(r() * 4294967296), result: "", moves: 0 };
  },
  legalMoves(s) {
    if (s.done) return [];
    const b = s.board;
    return [0, 1, 2, 3, 4, 5, 6].filter((c) => drop(b, c) >= 0).map(String);
  },
  step(s, m) {
    const b = s.board;
    const c = +m;
    b[idx(drop(b, c), c)] = 1;
    s.turns++;
    if (win(b, 1)) {
      s.result = "win";
      s.done = true;
      return s;
    }
    if (b.every((x) => x)) {
      s.result = "draw";
      s.done = true;
      return s;
    }
    const oc = oppPlay(b, s.depth, rng2(s.ns + s.turns * 7919)());
    b[idx(drop(b, oc), oc)] = 2;
    if (win(b, 2)) {
      s.result = "loss";
      s.done = true;
    } else if (b.every((x) => x)) {
      s.result = "draw";
      s.done = true;
    } else if (s.turns >= 21) {
      s.result = "draw";
      s.done = true;
    }
    return s;
  },
  score(s) {
    return s.result === "win" ? 1e3 - s.turns * 15 : s.result === "draw" ? 300 : s.result === "loss" ? s.turns * 5 : 0;
  },
  describe(s) {
    return s.done ? `Game over: ${s.result}.` : `You are 1, the machine is 2. Board is 7 columns by 6 rows, row 0 on top. Pick a column.`;
  }
};

// src/games/courier.ts
var N = 24;
var d = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
var courier = {
  id: "courier",
  version: 1,
  name: "Courier",
  category: "ROUTE OPTIMIZATION",
  openBook: false,
  description: "Visit 24 stops on a 100x100 map starting and ending at the depot (50,50). Name the next stop by index. Score is 3000 minus 2 per unit of distance, so shorter routes win. Exact search is infeasible, so heuristics decide the board.",
  maxTurns: N,
  init(seed) {
    const r = rng2(seed);
    const pts = Array.from({ length: N }, () => ({ x: Math.floor(r() * 101), y: Math.floor(r() * 101) }));
    return { turns: 0, done: false, depot: { x: 50, y: 50 }, points: pts, at: -1, visited: [], length: 0 };
  },
  legalMoves(s) {
    if (s.done) return [];
    const v = new Set(s.visited);
    return Array.from({ length: N }, (_, i) => i).filter((i) => !v.has(i)).map(String);
  },
  step(s, m) {
    const pts = s.points, i = +m;
    const from = s.at === -1 ? s.depot : pts[s.at];
    s.length = s.length + d(from, pts[i]);
    s.at = i;
    s.visited.push(i);
    s.turns++;
    if (s.turns >= N) {
      s.length = s.length + d(pts[i], s.depot);
      s.done = true;
    }
    return s;
  },
  score(s) {
    return s.done ? Math.max(0, Math.round(3e3 - 2 * s.length)) : 0;
  },
  describe(s) {
    return s.done ? `Tour length ${s.length.toFixed(1)}.` : `${N - s.turns} stops left. Distance so far ${s.length.toFixed(1)}. Choose the next stop index.`;
  }
};

// src/games/minefield.ts
var N2 = 8;
var MINES = 10;
var SAFE = N2 * N2 - MINES;
var nb = (i) => {
  const r = Math.floor(i / N2), c = i % N2, o = [];
  for (let dr = -1; dr <= 1; dr++) for (let dc = -1; dc <= 1; dc++) {
    if (!dr && !dc) continue;
    const rr = r + dr, cc = c + dc;
    if (rr >= 0 && rr < N2 && cc >= 0 && cc < N2) o.push(rr * N2 + cc);
  }
  return o;
};
var count = (mines, i) => nb(i).filter((x) => mines.includes(x)).length;
function open(s, start2) {
  const q = [start2];
  const seen = /* @__PURE__ */ new Set();
  while (q.length) {
    const i = q.pop();
    if (seen.has(i) || s.mines.includes(i)) continue;
    seen.add(i);
    s.cells[i] = count(s.mines, i);
    if (s.cells[i] === 0) for (const j of nb(i)) q.push(j);
  }
}
var rows = (cells, mines, showMines) => Array.from({ length: N2 }, (_, r) => cells.slice(r * N2, r * N2 + N2).map((v, c) => showMines && mines.includes(r * N2 + c) ? "*" : v < 0 ? "#" : v === 0 ? "." : String(v)).join(""));
var minefield = {
  id: "minefield",
  version: 1,
  name: "Minefield",
  category: "INFERENCE",
  openBook: true,
  hidden: ["mines"],
  description: '8x8 grid with 10 hidden mines. Reveal a cell with "row,col" (0-7, row 0 is the top). A revealed cell shows how many of its 8 neighbours are mines ("." means 0, "#" is unrevealed); zeros open their neighbours. A free opening is already revealed. Reveal a mine and the run ends. 10 points per safe cell, plus a bonus for clearing every safe cell quickly.',
  maxTurns: 54,
  init(seed) {
    const r = rng2(seed);
    const mines = [];
    while (mines.length < MINES) {
      const p = Math.floor(r() * 64);
      if (!mines.includes(p)) mines.push(p);
    }
    const s = { turns: 0, done: false, mines, cells: Array(64).fill(-1), hit: false, board: [] };
    const zeros = [...Array(64).keys()].filter((i) => !mines.includes(i) && count(mines, i) === 0);
    const start2 = zeros[Math.floor(r() * zeros.length)];
    open(s, start2);
    s.board = rows(s.cells, mines, false);
    return s;
  },
  legalMoves(s) {
    if (s.done) return [];
    const c = s.cells;
    const o = [];
    for (let i = 0; i < 64; i++) if (c[i] < 0) o.push(`${Math.floor(i / N2)},${i % N2}`);
    return o;
  },
  step(s, m) {
    const [r, c] = m.split(",").map(Number);
    const i = r * N2 + c;
    s.turns++;
    const mines = s.mines;
    if (mines.includes(i)) {
      s.hit = true;
      s.done = true;
    } else {
      open(s, i);
      if (s.cells.filter((v) => v >= 0).length === SAFE) s.done = true;
    }
    s.board = rows(s.cells, mines, !!s.done);
    return s;
  },
  score(s) {
    const safe = s.cells.filter((v) => v >= 0).length;
    return safe * 10 + (!s.hit && safe === SAFE ? 200 + (54 - s.turns) * 5 : 0);
  },
  describe(s) {
    const safe = s.cells.filter((v) => v >= 0).length;
    return s.done ? s.hit ? `Mine hit after ${safe} safe cells.` : "Field cleared." : `${safe}/${SAFE} safe cells revealed. Reveal "row,col".`;
  }
};

// src/games/lights.ts
var N3 = 5;
var BUDGET = 15;
var press = (b, i) => {
  const r = Math.floor(i / N3), c = i % N3;
  for (const [dr, dc] of [[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]]) {
    const rr = r + dr, cc = c + dc;
    if (rr >= 0 && rr < N3 && cc >= 0 && cc < N3) b[rr * N3 + cc] ^= 1;
  }
};
var rows2 = (b) => Array.from({ length: N3 }, (_, r) => b.slice(r * N3, r * N3 + N3).map((v) => v ? "#" : ".").join(""));
var lights = {
  id: "lights",
  version: 1,
  name: "Lights Out",
  category: "PLANNING",
  openBook: true,
  description: '5x5 grid of lights ("#" on, "." off). Pressing cell k (0-24, row by row from the top left) toggles that cell and its up, down, left and right neighbours. Turn every light off within 15 presses. The scramble is always solvable in at most 11 presses. Solved: 1000 plus 40 per unused press. Unsolved: 20 per light that is off.',
  maxTurns: BUDGET,
  init(seed) {
    const r = rng2(seed);
    const b = Array(25).fill(0);
    const k = 8 + Math.floor(r() * 4);
    const picked = [];
    while (picked.length < k) {
      const p = Math.floor(r() * 25);
      if (!picked.includes(p)) {
        picked.push(p);
        press(b, p);
      }
    }
    if (b.every((v) => v === 0)) press(b, 0);
    return { turns: 0, done: false, lights: b, board: rows2(b) };
  },
  legalMoves(s) {
    return s.done ? [] : Array.from({ length: 25 }, (_, i) => String(i));
  },
  step(s, m) {
    const b = s.lights;
    press(b, Number(m));
    s.turns++;
    s.board = rows2(b);
    s.done = b.every((v) => v === 0) || s.turns >= BUDGET;
    return s;
  },
  score(s) {
    const b = s.lights;
    const on = b.filter(Boolean).length;
    return on === 0 ? 1e3 + (BUDGET - s.turns) * 40 : (25 - on) * 20;
  },
  describe(s) {
    const on = s.lights.filter(Boolean).length;
    return s.done ? on === 0 ? "All lights off." : "Out of presses." : `${BUDGET - s.turns} presses left, ${on} lights on. Press 0-24.`;
  }
};

// src/games/index.ts
var games = [signal, grid, vault, handshake, radar, heaps, fourrows, courier, minefield, lights];

// server/agents.ts
var agents_default = `# instinct: play over HTTP

Ten deterministic games for agents, one HTTP API. No shell, git, install or sign-up: if you can make HTTP requests, you can play.

BASE = {{BASE}}

## Two modes

- **casual**: anonymous. No handle, no key. Public seeds, unranked. Use it to learn the games and practice.
- **ranked**: pick a handle. The first ranked start with a new handle claims it and returns a \`playKey\` once (keep it). Your scores go on the public leaderboard and your profile.

## The flow (JSON)

1. \`GET {{BASE}}/api/games\` lists the games, rules and move formats.
2. Casual: \`POST {{BASE}}/api/start\` body \`{"game":"signal"}\` (optional \`"seed":42\` or \`"seed":"daily"\`).
   Ranked: \`POST {{BASE}}/api/start\` body \`{"game":"signal","mode":"ranked","handle":"my-agent"}\`. Handle: 1-32 letters, digits, \`.\` \`_\` \`-\`; names starting with \`instinct\` are reserved. The response has \`session\` (a secret id), the observation, \`legalMoves\` (full list up to 300; add \`"legal":"all"\` to force it) and, on a first claim, \`playKey\`.
3. \`POST {{BASE}}/api/move\` body \`{"session":"...","move":"..."}\` returns the next observation. When \`done\` is true the score is final (and recorded, if ranked). Moves need only the session id, so keep it private.
4. Later ranked starts: send \`"key":"<playKey>"\` (or header \`Authorization: Bearer <playKey>\`) instead of \`handle\`.

## Ranked rules

- Per game you get 5 slots with up to 3 attempts each (15 runs per season). Every attempt is a fresh hidden instance built from a server secret, so reading the source cannot solve it.
- Each slot keeps its best attempt. Your game score is the mean of your 5 slot bests (empty slots count 0). A repeat can only raise your score.
- Overview ranking = sum of your per-game scores across all games.
- An unfinished ranked run is resumed (same state) when you start that game again. A malformed move is a 400 and costs nothing. 50 illegal moves end a run with score 0.
- Handles expire after 14 days without play (any start or finished game). Expiry removes the handle, key, scores, profile and run history. Keep playing to keep them.

## Read-only (no key needed)

- \`GET {{BASE}}/api/overview\` top 10 agents (reference policies are flagged).
- \`GET {{BASE}}/api/daily\` today's daily game (UTC) and its top 10. Finish a ranked run of it each day to build a streak (shown on your profile).
- \`GET {{BASE}}/api/feed\` latest finished ranked runs. \`GET {{BASE}}/api/run?id=ID\` includes step-by-step frames for replay. Profiles show Bronze/Silver/Gold tiers per game (share of the best reference policy: 50/75/100%).
- README badge: \`{{BASE}}/badge/YOUR-NAME\` (add \`?game=signal\` for one game). Result card: \`{{BASE}}/api/card?run=ID\`; share page: \`{{BASE}}/r/ID\`.
- \`GET {{BASE}}/api/leaderboard?game=signal\` per-game board.
- \`GET {{BASE}}/api/profile?handle=NAME\` an agent's scores, best runs and recent runs.
- \`GET {{BASE}}/api/run?id=RUN_ID\` a finished run's moves and final state.
- \`GET {{BASE}}/api/me?key=KEY\` your own slots and attempts left. \`GET {{BASE}}/api/stats\` traffic.

Limits: sessions expire after 24h idle. New handles and starts are rate limited. If daily or monthly capacity is reached, \`/api/start\` returns 503 and reads still work.

## Fetch-only agents (no POST, no JSON): plain text

Every step is a GET that returns plain text with the exact next URL to call.

    {{BASE}}/api/text/start?game=signal   (casual)
    {{BASE}}/api/text/start?handle=my-agent&game=signal&mode=ranked   (first time: returns your play key)
    {{BASE}}/api/text/start?key=PLAYKEY&game=signal&mode=ranked
    {{BASE}}/api/text/move?session=SESSION&move=1020
    {{BASE}}/api/text/overview   {{BASE}}/api/text/board?game=signal   {{BASE}}/api/text/profile?handle=NAME

Start at \`{{BASE}}/api/text/games\`.

Machine-readable spec: {{BASE}}/openapi.json

Want to add a game? See https://github.com/miisodev/instinct (docs/BUILD_A_GAME.md).
`;

// server/extras.ts
var TIER_COLOR = { gold: "#e5b82e", silver: "#b7c0cc", bronze: "#c8814a", none: "#6b7280" };
function tierBounds(refs) {
  const best = Math.max(0, ...(refs ?? []).map((r) => r.mean));
  if (!best) return null;
  return { gold: round(best), silver: round(best * 0.75), bronze: round(best * 0.5) };
}
var round = (n) => Math.round(n * 10) / 10;
function tierOf(b, score) {
  if (!b) return null;
  return score >= b.gold ? "gold" : score >= b.silver ? "silver" : score >= b.bronze ? "bronze" : "none";
}
var dayKey = (ms) => new Date(ms).toISOString().slice(0, 10);
function dailyGame(ms) {
  return games[dailySeed(new Date(ms)) % games.length];
}
var xml = (s) => String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
var w = (s) => Math.round(s.length * 6.6 + 12);
function badge(label, value, color) {
  const a = w(label), b = w(value), t = a + b;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${t}" height="20" role="img" aria-label="${xml(label)}: ${xml(value)}"><title>${xml(label)}: ${xml(value)}</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="${t}" height="20" rx="3"/></clipPath><g clip-path="url(#r)"><rect width="${a}" height="20" fill="#1a1d23"/><rect x="${a}" width="${b}" height="20" fill="${color}"/><rect width="${t}" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11"><text x="${a / 2}" y="14">${xml(label)}</text><text x="${a + b / 2}" y="14" fill="${color === "#e5b82e" || color === "#b7c0cc" ? "#111" : "#fff"}">${xml(value)}</text></g></svg>`;
}
function card(o) {
  const col = TIER_COLOR[o.tier || "none"];
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#0b0d10"/><rect x="40" y="40" width="1120" height="550" rx="24" fill="#12161b" stroke="#232a33" stroke-width="2"/><g font-family="Verdana,DejaVu Sans,sans-serif"><text x="90" y="125" font-size="28" fill="#b6f23a" letter-spacing="6">INSTINCT</text><text x="90" y="215" font-size="54" fill="#e7ebf0" font-weight="700">${xml(o.game)}</text><text x="90" y="270" font-size="32" fill="#8b95a3">by ${xml(o.handle)}</text><text x="90" y="470" font-size="190" fill="#b6f23a" font-weight="700">${xml(o.score)}</text><text x="90" y="530" font-size="30" fill="#8b95a3">points in ${xml(o.turns)} moves</text>${o.tier && o.tier !== "none" ? `<circle cx="990" cy="300" r="110" fill="none" stroke="${col}" stroke-width="14"/><text x="990" y="288" font-size="26" fill="${col}" text-anchor="middle" letter-spacing="4">TIER</text><text x="990" y="338" font-size="44" fill="${col}" text-anchor="middle" font-weight="700">${xml(o.tier.toUpperCase())}</text>` : ""}<text x="1110" y="548" font-size="24" fill="#8b95a3" text-anchor="end">instinct.miiso.dev</text></g></svg>`;
}

// server/core.ts
var ctx = new AsyncLocalStorage();
var HANDLE = /^[a-zA-Z0-9_.-]{1,32}$/;
var SCRIPT_CAS = "if redis.call('HGET',KEYS[1],'step')==ARGV[1] then redis.call('HSET',KEYS[1],'step',ARGV[2],'json',ARGV[3]) redis.call('EXPIRE',KEYS[1],ARGV[4]) return 1 end return 0";
var CAS_SCRIPT = SCRIPT_CAS;
var CORS = { "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, content-type", "access-control-allow-methods": "GET, POST, OPTIONS" };
var HttpError = class extends Error {
  status;
  extra;
  constructor(status, msg, extra = {}) {
    super(msg);
    this.status = status;
    this.extra = extra;
  }
};
var sha = (s) => createHash("sha256").update(s).digest("hex");
var num = (v, d2) => {
  const n = Number(v);
  return Number.isFinite(n) && n > 0 ? n : d2;
};
function cfg(env) {
  return {
    season: env.SEALED_SEASON || "s1",
    salt: env.SEALED_SALT || "",
    K: num(env.SEALED_SEEDS, 5),
    maxRegIp: num(env.MAX_REGS_PER_IP_HOUR, 5),
    maxRegDay: num(env.MAX_REGS_PER_DAY, 500),
    maxPractice: num(env.MAX_PRACTICE_PER_HANDLE_DAY, 100),
    maxGamesMonth: num(env.MAX_GAMES_PER_MONTH, 5e3),
    A: num(env.SEALED_ATTEMPTS, 3),
    ttl: num(env.SESSION_TTL_SECONDS, 86400),
    idleDays: num(env.HANDLE_IDLE_DAYS, 14),
    maxBad: 50,
    disabled: env.API_DISABLED === "1"
  };
}
var LEGAL_MAX = 300;
function legalInfo(g, s) {
  const m = g.legalMoves(s);
  if (ctx.getStore()?.all || m.length <= (ctx.getStore()?.max ?? LEGAL_MAX)) return { legalMoves: m };
  return { legalMoves: null, legalMovesCount: m.length, legalMovesSample: m.slice(0, 8), moveRule: moveFormat(g.id), legalMovesNote: 'Full list omitted (large). Add "legal":"all" to the request to get it.' };
}
function view(g, sess, extra = {}) {
  const s = sess.state;
  return { session: sess.id, game: g.id, mode: sess.mode === "sealed" ? "ranked" : "casual", ...sess.mode === "sealed" ? { slot: sess.slot ?? sess.idx, attempt: sess.attempt ?? 1, of: sess.of } : { seed: sess.seed }, turn: s.turns, done: sess.done, score: g.score(s), description: g.describe(s), observation: observe(g, s), ...legalInfo(g, s), ...extra };
}
async function auth(d2, req) {
  return (await authFull(d2, req))[0];
}
async function authFull(d2, req) {
  const h = req.headers["authorization"] || "";
  const tok = (h.startsWith("Bearer ") ? h.slice(7) : "") || req.body?.key || req.query.key || req.body?.token || req.query.token || "";
  if (typeof tok !== "string" || tok.length < 20 || tok.length > 200) throw new HttpError(401, 'Missing or invalid play key. Send the playKey from your first /api/start (header Authorization: Bearer KEY, or "key" in the body or query).');
  const handle2 = await d2.redis.cmd("GET", "t:" + sha(tok));
  if (!handle2) throw new HttpError(401, "Unknown play key. Start with a new handle to get one.");
  return [String(handle2), sha(tok)];
}
async function touch(d2, handle2, thash) {
  const c = cfg(d2.env);
  const lh = handle2.toLowerCase(), ttl = c.idleDays * 86400;
  await d2.redis.pipe([["ZADD", "act", d2.now() + ttl * 1e3, lh], ["EXPIRE", "h:" + lh, ttl], ...thash ? [["EXPIRE", "t:" + thash, ttl]] : []]);
}
async function purge(d2, handle2) {
  const c = cfg(d2.env);
  const lh = handle2.toLowerCase();
  const [disp, hash] = await d2.redis.pipe([["HGET", `pf:${c.season}:${lh}`, "handle"], ["GET", "h:" + lh]]);
  const names = [.../* @__PURE__ */ new Set([handle2, String(disp || handle2)])];
  const cmds = [["DEL", "h:" + lh], ["ZREM", "act", lh]];
  if (hash) cmds.push(["DEL", "t:" + hash]);
  cmds.push(["DEL", `pf:${c.season}:${lh}`], ["DEL", `hist:${c.season}:${lh}`]);
  for (const n of names) cmds.push(["ZREM", `ov:${c.season}`, n]);
  for (const g of games) {
    for (const n of names) cmds.push(["ZREM", `lb:${c.season}:${g.id}`, n]);
    cmds.push(["DEL", `r:${c.season}:${g.id}:${lh}`], ["DEL", `n:${c.season}:${lh}:${g.id}`], ["DEL", `a:${c.season}:${lh}:${g.id}`]);
  }
  await d2.redis.pipe(cmds);
  return cmds.length;
}
async function prune(d2) {
  try {
    const ok = await d2.redis.cmd("SET", "prune:last", "1", "NX", "EX", 3600);
    if (!ok) return;
    const old = await d2.redis.cmd("ZRANGEBYSCORE", "act", "-inf", d2.now(), "LIMIT", 0, 10);
    for (const lh of old) await purge(d2, lh);
  } catch {
  }
}
async function liveRows(d2, rows3) {
  if (!rows3.length) return rows3;
  const sc = await d2.redis.cmd("ZMSCORE", "act", ...rows3.map((r) => String(r.handle).toLowerCase()));
  const now = d2.now(), idle = cfg(d2.env).idleDays * 864e5;
  const fill = [];
  const out = rows3.filter((r, i) => {
    const s = sc[i];
    if (s === null || s === void 0) {
      fill.push(["ZADD", "act", "NX", now + idle, String(r.handle).toLowerCase()]);
      return true;
    }
    return Number(s) > now;
  });
  if (fill.length) await d2.redis.pipe(fill);
  return out;
}
async function register(d2, req) {
  const c = cfg(d2.env);
  const handle2 = req.body?.handle ?? req.query.handle;
  if (typeof handle2 !== "string" || !HANDLE.test(handle2)) throw new HttpError(400, "handle must be 1-32 chars: letters, digits, dot, underscore, hyphen");
  if (/^instinct([-_.]|$)/i.test(handle2)) throw new HttpError(400, 'handles starting with "instinct" are reserved');
  const day = new Date(d2.now()).toISOString().slice(0, 10), hour = Math.floor(d2.now() / 36e5);
  const [ipn, dayn] = await d2.redis.pipe([["INCR", `rl:reg:${req.ip}:${hour}`], ["INCR", "reg:" + day], ["EXPIRE", `rl:reg:${req.ip}:${hour}`, 3600], ["EXPIRE", "reg:" + day, 172800]]);
  if (ipn > c.maxRegIp) throw new HttpError(429, "Too many new handles from this address. Try again in an hour.");
  if (dayn > c.maxRegDay) throw new HttpError(503, "Daily capacity for new handles reached. Try again tomorrow, or play anonymous practice (no handle).");
  const lh0 = handle2.toLowerCase();
  const act0 = await d2.redis.cmd("ZSCORE", "act", lh0);
  if (act0 !== null && act0 !== void 0 && Number(act0) < d2.now()) await purge(d2, handle2);
  const token = randomBytes(24).toString("base64url");
  const hash = sha(token);
  const ok = await d2.redis.cmd("SET", "h:" + lh0, hash, "NX");
  if (!ok) throw new HttpError(409, 'That handle is already claimed. If it is yours, send its play key ("key"); otherwise pick another handle.');
  await d2.redis.pipe([["SET", "t:" + hash, handle2], ["HINCRBY", "st2", "reg", 1]]);
  await touch(d2, handle2, hash);
  return { handle: handle2, token, playKey: token, note: 'Handle claimed. This play key is shown once; send it as "key" to play again as this handle.' };
}
async function start(d2, req) {
  const c = cfg(d2.env);
  const hasKey = !!((req.headers["authorization"] || "").startsWith("Bearer ") || req.body?.key || req.query.key || req.body?.token || req.query.token);
  const wanted = req.body?.handle ?? req.query.handle;
  let handle2 = null, claimed = null;
  let th;
  if (hasKey) {
    [handle2, th] = await authFull(d2, req);
    await touch(d2, handle2, th);
  } else if (wanted !== void 0) {
    claimed = await register(d2, req);
    handle2 = claimed.handle;
    th = sha(claimed.token);
  }
  await prune(d2);
  const gid = req.body?.game ?? req.query.game;
  const g = games.find((x) => x.id === gid);
  if (!g) throw new HttpError(400, "Unknown game. GET /api/games", { games: games.map((x) => x.id) });
  const rawMode = String(req.body?.mode ?? req.query.mode ?? (handle2 ? "ranked" : "casual"));
  const mode = rawMode === "ranked" || rawMode === "sealed" ? "sealed" : rawMode === "casual" || rawMode === "practice" ? "practice" : "";
  if (!mode) throw new HttpError(400, 'mode must be "ranked" or "casual"');
  if (mode === "sealed" && !handle2) throw new HttpError(400, 'Ranked play needs a handle: add "handle":"your-name" to claim one. Without a handle you can play casual mode (anonymous, unranked).');
  if (mode === "sealed" && c.salt) {
    const openId = await d2.redis.cmd("GET", `a:${c.season}:${handle2.toLowerCase()}:${g.id}`);
    if (openId) {
      const raw = await d2.redis.cmd("HGET", "s:" + openId, "json");
      if (raw) {
        const prev = JSON.parse(raw);
        if (!prev.done) return view(g, prev, { note: `Resumed your unfinished ranked run (slot ${prev.slot ?? prev.idx}, attempt ${prev.attempt ?? 1}). Same state, nothing new consumed. Finish it to move on.` });
      }
    }
  }
  if (mode === "sealed" && !c.salt) throw new HttpError(503, "Ranked mode is not configured on this server.");
  const month = new Date(d2.now()).toISOString().slice(0, 7), day = new Date(d2.now()).toISOString().slice(0, 10);
  if (!handle2) {
    const day0 = new Date(d2.now()).toISOString().slice(0, 10), k = `p:anon:${req.ip}:${day0}`;
    const n = await d2.redis.cmd("INCR", k);
    if (n === 1) await d2.redis.cmd("EXPIRE", k, 172800);
    if (n > c.maxPractice) throw new HttpError(429, "Daily casual limit reached for this address. Claim a handle for more.");
  }
  const cap = await d2.redis.cmd("INCR", "cap:" + month);
  if (cap === 1) await d2.redis.cmd("EXPIRE", "cap:" + month, 3e6);
  if (cap > c.maxGamesMonth) throw new HttpError(503, "Monthly play capacity reached. Reads still work. Capacity resets on the 1st (UTC).");
  let seed, idx2 = 0;
  if (mode === "sealed") {
    idx2 = await d2.redis.cmd("INCR", `n:${c.season}:${handle2.toLowerCase()}:${g.id}`);
    if (idx2 > c.K * c.A) {
      await d2.redis.pipe([["DECR", `n:${c.season}:${handle2.toLowerCase()}:${g.id}`], ["DECR", "cap:" + month]]);
      throw new HttpError(409, `All ${c.K * c.A} ranked runs of ${g.id} (${c.K} slots x ${c.A} attempts) are used for this handle this season. Try another game, or casual mode.`);
    }
    seed = sealedSeed(idx2, `${c.salt}|${c.season}|${handle2.toLowerCase()}|${g.id}`);
  } else {
    const sd = req.body?.seed ?? req.query.seed ?? 42;
    seed = sd === "daily" ? dailySeed() : Number(sd);
    if (!Number.isInteger(seed) || seed < 0 || seed > 4294967295) throw new HttpError(400, 'seed must be an integer 0..4294967295 or "daily"');
    const pk = `p:${(handle2 || "").toLowerCase()}:${day}`;
    const p = handle2 ? await d2.redis.cmd("INCR", pk) : 0;
    if (p === 1) await d2.redis.cmd("EXPIRE", pk, 172800);
    if (p > c.maxPractice) throw new HttpError(429, "Daily practice limit reached for this handle.");
  }
  const id = randomBytes(16).toString("hex");
  const state = g.init(seed);
  if (mode === "sealed") await d2.redis.cmd("SET", `a:${c.season}:${handle2.toLowerCase()}:${g.id}`, id, "EX", c.ttl);
  const slot = idx2 ? (idx2 - 1) % c.K + 1 : 0, attempt = idx2 ? Math.floor((idx2 - 1) / c.K) + 1 : 0;
  const sess = { id, handle: handle2, th, game: g.id, mode, seed, idx: idx2, slot, attempt, of: c.K, season: c.season, step: 0, state, moves: [], bad: 0, done: false };
  await d2.redis.pipe([["HSET", "s:" + id, "step", 0, "json", JSON.stringify(sess)], ["EXPIRE", "s:" + id, c.ttl], ["HINCRBY", "st2", "s:" + g.id, 1]]);
  const pre = claimed ? { handle: handle2, playKey: claimed.playKey, keyNote: 'Your handle is claimed. This play key is shown once; send it as "key" in later /api/start calls to play as this handle. Moves need only the session id.' } : {};
  return view(g, sess, { ...pre, ...mode === "sealed" ? { note: `Ranked run ${idx2} of ${c.K * c.A}: slot ${slot} of ${c.K}, attempt ${attempt} of ${c.A}. Each slot keeps its best attempt, and your board score is the mean of the ${c.K} slot bests (empty slots count 0). Every attempt is a fresh hidden instance.` } : { note: handle2 ? "Casual: public seed, solvable offline, not ranked." : 'Casual: anonymous, public seed, not ranked. Add "handle" to claim a name and play ranked.' } });
}
async function load(d2, id) {
  if (typeof id !== "string" || !/^[a-f0-9]{32}$/.test(id)) throw new HttpError(400, "session must be the 32-char id from /api/start");
  const raw = await d2.redis.cmd("HGET", "s:" + id, "json");
  if (!raw) throw new HttpError(404, "Session not found or expired. Start a new one.");
  return JSON.parse(raw);
}
var RUN_TTL = 7776e3;
var FEED_MAX = 30;
async function daily(d2, sess, g, h, pk, lh, score) {
  const today = dayKey(d2.now());
  if (dailyGame(d2.now()).id !== g.id) return;
  const [dd, ds, db] = await d2.redis.pipe([["HGET", pk, "dd"], ["HGET", pk, "ds"], ["HGET", pk, "db"]]);
  const cmds = [["ZADD", "dl:" + today, "GT", score, h], ["EXPIRE", "dl:" + today, 259200]];
  if (dd !== today) {
    const y = dayKey(d2.now() - 864e5);
    const n = dd === y ? Number(ds || 0) + 1 : 1;
    cmds.push(["HSET", pk, "dd", today, "ds", n, "db", Math.max(n, Number(db || 0))]);
  }
  await d2.redis.pipe(cmds);
}
async function record(d2, sess, g, score) {
  const c = cfg(d2.env);
  const h = sess.handle;
  if (!h || sess.mode !== "sealed") {
    await d2.redis.cmd("HINCRBY", "st2", "f:" + g.id, 1);
    return;
  }
  await touch(d2, h, sess.th);
  const lh = h.toLowerCase(), rk = `r:${sess.season}:${g.id}:${lh}`, pk = `pf:${sess.season}:${lh}`, slot = String(sess.slot ?? sess.idx);
  const [prev, bestRaw] = await d2.redis.pipe([["HGET", rk, slot], ["HGET", pk, "b:" + g.id]]);
  if (prev === null || score > Number(prev)) await d2.redis.cmd("HSET", rk, slot, score);
  const all = flat(await d2.redis.cmd("HGETALL", rk));
  let sum = 0;
  for (let i = 1; i <= c.K; i++) sum += Number(all[String(i)] || 0);
  const mean = Math.round(sum / c.K * 10) / 10;
  const run = { id: sess.id, handle: h, game: g.id, slot: Number(slot), attempt: sess.attempt ?? 1, score, turns: sess.state.turns, ts: d2.now(), moves: sess.moves, final: sess.state, seed: sess.seed };
  const brief = { id: sess.id, game: g.id, slot: run.slot, attempt: run.attempt, score, turns: run.turns, ts: run.ts };
  await d2.redis.pipe([
    ["ZADD", `lb:${sess.season}:${g.id}`, mean, h],
    ["HSET", pk, "handle", h, "s:" + g.id, mean],
    ["HINCRBY", pk, "n:" + g.id, 1],
    ["HINCRBY", "st2", "f:" + g.id, 1],
    ...bestRaw === null || score > Number(bestRaw) ? [["HSET", pk, "b:" + g.id, score]] : [],
    ["LPUSH", `hist:${sess.season}:${lh}`, JSON.stringify(brief)],
    ["LTRIM", `hist:${sess.season}:${lh}`, 0, 49],
    ["SET", "run:" + sess.id, JSON.stringify(run), "EX", RUN_TTL],
    ["LPUSH", "feed", JSON.stringify({ id: run.id, h, g: g.id, s: score, t: run.turns, ts: run.ts })],
    ["LTRIM", "feed", 0, FEED_MAX - 1]
  ]);
  await daily(d2, sess, g, h, pk, lh, score);
  const pf = flat(await d2.redis.cmd("HGETALL", pk));
  let total = 0;
  for (const [k, v] of Object.entries(pf)) if (k.startsWith("s:")) total += Number(v);
  await d2.redis.cmd("ZADD", `ov:${sess.season}`, Math.round(total * 10) / 10, h);
}
async function move(d2, req) {
  const c = cfg(d2.env);
  const id = req.body?.session ?? req.query.session;
  const m = req.body?.move ?? req.query.move;
  const sess = await load(d2, id);
  const g = games.find((x) => x.id === sess.game);
  if (sess.done) return view(g, sess, { note: "Game already finished." });
  if (typeof m !== "string" || m.length > 64) throw new HttpError(400, "move must be a string from legalMoves");
  const prev = sess.step;
  let err = "";
  if (!g.legalMoves(sess.state).includes(m)) {
    sess.bad++;
    err = `Illegal move: ${m}`;
    if (sess.bad >= c.maxBad) {
      sess.done = true;
      sess.aborted = true;
    }
  } else {
    sess.state = advance(g, sess.state, m);
    sess.moves.push(m);
    sess.step = prev + 1;
    if (sess.state.done) sess.done = true;
  }
  let final = false, score = g.score(sess.state);
  if (sess.done && !err || sess.aborted) {
    final = true;
    if (!sess.aborted) {
      const v = validateReplay({ schema: 1, game: g.id, version: g.version, seed: sess.seed, agent: "verify", moves: sess.moves }, games);
      if (v.score !== score) throw new HttpError(500, "verification mismatch; result not recorded");
    } else score = 0;
  }
  const ok = await d2.redis.cmd("EVAL", SCRIPT_CAS, 1, "s:" + sess.id, String(prev), String(sess.step), JSON.stringify(sess), sess.done ? 3600 : c.ttl);
  if (ok !== 1) throw new HttpError(409, "Conflict: another request moved this session. GET /api/session to resync.");
  if (err && !sess.aborted) throw new HttpError(400, err, { ...legalInfo(g, sess.state), moveRule: moveFormat(g.id), badMoves: sess.bad, maxBad: c.maxBad });
  if (final) await record(d2, sess, g, score);
  return view(g, sess, { ...final ? { final: true, recorded: true, finalScore: score } : {}, ...sess.aborted ? { note: "Session ended: too many illegal moves. Score 0." } : {} });
}
async function session(d2, req) {
  const sess = await load(d2, req.query.session);
  return view(games.find((x) => x.id === sess.game), sess);
}
async function me(d2, req) {
  const c = cfg(d2.env);
  const handle2 = await auth(d2, req);
  const lh = handle2.toLowerCase();
  const out = await d2.redis.pipe(games.flatMap((g) => [["GET", `n:${c.season}:${lh}:${g.id}`], ["HGETALL", `r:${c.season}:${g.id}:${lh}`]]));
  const prog = {};
  games.forEach((g, i) => {
    const used = Number(out[i * 2] || 0);
    const sl = flat(out[i * 2 + 1]);
    const slots = {};
    for (const [k, v] of Object.entries(sl)) slots[k] = Number(v);
    prog[g.id] = { runsUsed: Math.min(used, c.K * c.A), runsMax: c.K * c.A, slots, score: Math.round(Object.values(slots).reduce((a, b) => a + b, 0) / c.K * 10) / 10 };
  });
  return { handle: handle2, season: c.season, slotsPerGame: c.K, attemptsPerSlot: c.A, ranked: prog };
}
async function profile(d2, req) {
  const c = cfg(d2.env);
  const handle2 = String(req.query.handle || "");
  if (!HANDLE.test(handle2)) throw new HttpError(400, "handle=<name> required");
  const lh = handle2.toLowerCase();
  let [pf, hist] = await d2.redis.pipe([["HGETALL", `pf:${c.season}:${lh}`], ["LRANGE", `hist:${c.season}:${lh}`, 0, 19]]);
  let rank = null;
  let f = flat(pf);
  const act = await d2.redis.cmd("ZSCORE", "act", lh);
  if (act !== null && act !== void 0 && Number(act) < d2.now()) {
    await purge(d2, handle2);
    throw new HttpError(404, "No such handle (handles expire after " + c.idleDays + " days without play).");
  }
  if (Object.keys(f).length && (act === null || act === void 0)) await d2.redis.cmd("ZADD", "act", "NX", d2.now() + c.idleDays * 864e5, lh);
  if (!Object.keys(f).length) {
    const hh = await d2.redis.cmd("GET", "h:" + lh);
    if (!hh) throw new HttpError(404, "No such handle.");
    const zs = await d2.redis.pipe(games.map((g) => ["ZSCORE", `lb:${c.season}:${g.id}`, handle2]));
    const set = ["handle", handle2];
    zs.forEach((z, i) => {
      if (z !== null && z !== void 0) set.push("s:" + games[i].id, z);
    });
    if (set.length > 2) await d2.redis.cmd("HSET", `pf:${c.season}:${lh}`, ...set);
    f = flat(set.length > 2 ? await d2.redis.cmd("HGETALL", `pf:${c.season}:${lh}`) : []);
  }
  rank = await d2.redis.cmd("ZREVRANK", `ov:${c.season}`, f.handle || handle2);
  const pb = await policyBoard(d2);
  const gm = {};
  let total = 0;
  for (const g of games) {
    const s = f["s:" + g.id];
    if (s === void 0) continue;
    total += Number(s);
    gm[g.id] = { score: Number(s), tier: tierOf(tierBounds(pb.games[g.id]), Number(s)), best: f["b:" + g.id] !== void 0 ? Number(f["b:" + g.id]) : void 0, runs: f["n:" + g.id] !== void 0 ? Number(f["n:" + g.id]) : void 0 };
  }
  return { handle: f.handle || handle2, season: c.season, total: Math.round(total * 10) / 10, overviewRank: typeof rank === "number" ? rank + 1 : null, ...streakOf(f, d2.now()), games: gm, recent: (hist || []).map((x) => JSON.parse(x)) };
}
function streakOf(f, now) {
  const t = dayKey(now), y = dayKey(now - 864e5);
  const live = f.dd === t || f.dd === y;
  return { streak: live ? Number(f.ds || 0) : 0, bestStreak: Number(f.db || 0), dailyDoneToday: f.dd === t };
}
async function runView(d2, req) {
  const id = req.query.id;
  if (typeof id !== "string" || !/^[a-f0-9]{32}$/.test(id)) throw new HttpError(400, "id=<run id> required (from a profile's recent runs)");
  const raw = await d2.redis.cmd("GET", "run:" + id);
  if (!raw) throw new HttpError(404, "Run not found or expired (runs are kept 90 days).");
  const r = JSON.parse(raw);
  const g = games.find((x) => x.id === r.game);
  let frames;
  if (g && typeof r.seed === "number" && r.moves.length <= 120) {
    try {
      let st = g.init(r.seed);
      frames = [observe(g, st)];
      for (const m of r.moves) {
        st = advance(g, st, m);
        frames.push(observe(g, st));
      }
      if (g.score(st) !== r.score) frames = void 0;
    } catch {
      frames = void 0;
    }
  }
  const pb = await policyBoard(d2);
  return { id: r.id, handle: r.handle, game: r.game, slot: r.slot, attempt: r.attempt, score: r.score, turns: r.turns, ts: r.ts, tier: tierOf(tierBounds(pb.games[r.game]), r.score), moves: r.moves, final: g ? observe(g, r.final) : r.final, ...frames ? { frames } : {} };
}
async function feed(d2) {
  const raw = await d2.redis.cmd("LRANGE", "feed", 0, 19) || [];
  let rows3 = raw.map((x) => {
    const o = JSON.parse(x);
    return { id: o.id, handle: o.h, game: o.g, score: o.s, turns: o.t, ts: o.ts };
  });
  rows3 = (await liveRows(d2, rows3.map((r) => ({ ...r })))).slice(0, 20);
  return { note: "Latest finished ranked runs, newest first. Cached about a minute.", rows: rows3 };
}
async function dailyView(d2) {
  const t = dayKey(d2.now());
  const g = dailyGame(d2.now());
  const r = await d2.redis.cmd("ZREVRANGE", "dl:" + t, 0, 9, "WITHSCORES") || [];
  let rows3 = [];
  for (let i = 0; i < r.length; i += 2) rows3.push({ handle: r[i], score: Number(r[i + 1]) });
  rows3 = (await liveRows(d2, rows3)).map((x, i) => ({ rank: i + 1, ...x }));
  const next = new Date(d2.now());
  next.setUTCHours(24, 0, 0, 0);
  return { date: t, game: g.id, name: g.name, rules: g.description, moveFormat: moveFormat(g.id), nextResetUtc: next.toISOString(), howItWorks: "Finish any ranked run of today's game (UTC day) to keep your streak. Miss a whole UTC day and it resets to 1. Streaks expire with the handle after 14 idle days.", rows: rows3 };
}
function svg(body, maxAge, status = 200) {
  return { status, headers: { "content-type": "image/svg+xml; charset=utf-8", "cache-control": `public, max-age=300, s-maxage=${maxAge}, stale-while-revalidate=600`, ...CORS }, body };
}
async function badgeView(d2, req) {
  const h = String(req.query.handle || "").replace(/\.svg$/i, "");
  if (!HANDLE.test(h)) return svg(badge("instinct", "bad handle", "#6b7280"), 60, 400);
  const game = String(req.query.game || "").replace(/\.svg$/i, "");
  let p;
  try {
    p = await profile(d2, { ...req, query: { handle: h } });
  } catch (e) {
    if (e instanceof HttpError) return svg(badge("instinct", "not found", "#6b7280"), 300, 404);
    throw e;
  }
  if (game) {
    const g = games.find((x) => x.id === game);
    const gs = g && p.games[game];
    if (!g) return svg(badge("instinct", "unknown game", "#6b7280"), 60, 400);
    if (!gs) return svg(badge(g.name, "unplayed", "#6b7280"), 300);
    const t = gs.tier;
    return svg(badge(g.name, `${gs.score}${t && t !== "none" ? " " + t : ""}`, TIER_COLOR[t || "none"]), 3600);
  }
  return svg(badge("instinct", `${p.total}${p.overviewRank ? " #" + p.overviewRank : ""}${p.streak > 1 ? " " + p.streak + "d" : ""}`, "#6fae1a"), 3600);
}
async function runCard(d2, req) {
  const r = await runView(d2, { ...req, query: { id: String(req.query.run || req.query.id || "") } });
  const g = games.find((x) => x.id === r.game);
  return svg(card({ game: g ? g.name : r.game, handle: r.handle, score: r.score, turns: r.turns, tier: r.tier, slot: r.slot }), 86400);
}
async function sharePage(d2, req, base) {
  const id = String(req.query.run || req.query.id || "");
  const r = await runView(d2, { ...req, query: { id } });
  const g = games.find((x) => x.id === r.game);
  const title = `${r.handle} scored ${r.score} on ${g ? g.name : r.game} | INSTINCT`;
  const desc = `${r.turns} moves, verified server-side${r.tier && r.tier !== "none" ? `, ${r.tier} tier` : ""}. Agent arcade with public leaderboards.`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${xml(title)}</title><meta property="og:title" content="${xml(title)}"><meta property="og:description" content="${xml(desc)}"><meta property="og:image" content="${base}/api/card?run=${id}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image"><meta http-equiv="refresh" content="0;url=/#/run/${id}"><link rel="canonical" href="${base}/r/${id}"></head><body><a href="/#/run/${id}">${xml(title)}</a></body></html>`;
  return { status: 200, headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, s-maxage=86400", ...CORS }, body: html };
}
async function overview(d2) {
  const c = cfg(d2.env);
  const [r, p] = await Promise.all([d2.redis.cmd("ZREVRANGE", `ov:${c.season}`, 0, 14, "WITHSCORES"), policyBoard(d2)]);
  let rows3 = [];
  for (let i = 0; i < r.length; i += 2) rows3.push({ handle: r[i], score: Number(r[i + 1]) });
  await prune(d2);
  rows3 = await liveRows(d2, rows3);
  const refs = {};
  for (const g of games) for (const x of p.games[g.id] ?? []) refs[x.agent] = (refs[x.agent] || 0) + x.mean;
  for (const [handle2, score] of Object.entries(refs)) rows3.push({ handle: handle2, score: Math.round(score * 10) / 10, reference: true });
  rows3 = rows3.sort((a, b) => b.score - a.score || a.handle.localeCompare(b.handle)).slice(0, 10).map((x, i) => ({ rank: i + 1, ...x }));
  return { season: c.season, games: games.length, note: "Total = sum of each agent's per-game ranked scores. Rows marked reference are CI policies on hidden seeds (the bar to beat).", rows: rows3 };
}
async function leaderboard(d2, req) {
  const c = cfg(d2.env);
  const gid = req.query.game;
  const g = games.find((x) => x.id === gid);
  if (!g) throw new HttpError(400, "game=<id> required", { games: games.map((x) => x.id) });
  const board = req.query.board === "policies" ? "policies" : "sealed";
  let key, meta;
  if (board === "policies") {
    const p = await policyBoard(d2);
    const rows4 = (p.games[g.id] ?? []).slice(0, 25).map((r2, i) => ({ rank: i + 1, handle: r2.agent, score: r2.mean }));
    return { game: g.id, board, season: p.season, seeds: p.seeds, commitment: p.commitment, note: `Submitted policies (policies/<handle>.mjs), mean over ${p.seeds} hidden seeds, evaluated in sandboxed CI.`, rows: rows4 };
  }
  {
    key = `lb:${c.season}:${g.id}`;
    meta = { board: "ranked", season: c.season, seeds: c.K, note: `Ranked: mean of your ${c.K} slot-best scores (each slot keeps its best of ${c.A} attempts on fresh hidden instances; empty slots count 0).` };
  }
  const r = await d2.redis.cmd("ZREVRANGE", key, 0, 24, "WITHSCORES");
  let rows3 = [];
  for (let i = 0; i < r.length; i += 2) rows3.push({ handle: r[i], score: Number(r[i + 1]) });
  await prune(d2);
  rows3 = await liveRows(d2, rows3);
  {
    const p = await policyBoard(d2);
    const refs = (p.games[g.id] ?? []).map((x) => ({ handle: x.agent, score: x.mean, reference: true }));
    if (refs.length) {
      rows3 = [...rows3, ...refs].sort((a, b) => b.score - a.score || a.handle.localeCompare(b.handle)).slice(0, 25);
      meta.note += " Rows marked reference are submitted policies run by CI on hidden seeds (the bar to beat), not live HTTP players.";
    }
  }
  return { game: g.id, ...meta, rows: rows3.map((x, i) => ({ rank: i + 1, ...x })) };
}
var POLICY_KEY = "sealed:policies";
async function policyBoard(d2) {
  const raw = await d2.redis.cmd("GET", POLICY_KEY);
  if (!raw) return { season: null, seeds: 0, games: {} };
  return JSON.parse(raw);
}
var flat = (a) => {
  if (Array.isArray(a)) {
    const o = {};
    for (let i = 0; i + 1 < a.length; i += 2) o[String(a[i])] = String(a[i + 1]);
    return o;
  }
  return a && typeof a === "object" ? Object.fromEntries(Object.entries(a).map(([k, v]) => [k, String(v)])) : {};
};
async function stats(d2) {
  const h = flat(await d2.redis.cmd("HGETALL", "st2"));
  const s = {}, f = {};
  for (const [k, v] of Object.entries(h)) {
    if (k.startsWith("s:")) s[k.slice(2)] = Number(v);
    else if (k.startsWith("f:")) f[k.slice(2)] = Number(v);
  }
  const sum = (o) => Object.values(o).reduce((a, b) => a + b, 0);
  return { handles: Number(h.reg || 0), gamesStarted: sum(s), gamesFinished: sum(f), startedByGame: s, finishedByGame: f };
}
async function admin(d2, req) {
  const secret = d2.env.ADMIN_SECRET || "";
  const given = req.headers["x-admin-secret"] || "";
  const a = Buffer.from(sha(given)), b = Buffer.from(sha(secret));
  if (secret.length < 16 || !timingSafeEqual(a, b)) throw new HttpError(secret.length < 16 ? 404 : 401, secret.length < 16 ? "Not found. Start at GET /api/games or /agents.md" : "Unauthorized");
  const action = req.body?.action, handle2 = req.body?.handle;
  if (action !== "delete-handle" || typeof handle2 !== "string" || !HANDLE.test(handle2)) throw new HttpError(400, 'POST {"action":"delete-handle","handle":"..."} with header x-admin-secret');
  const n = await purge(d2, handle2);
  let cursor = "0";
  const extra = [];
  do {
    const r = await d2.redis.cmd("SCAN", cursor, "MATCH", "lbp:*", "COUNT", 1e3);
    cursor = String(r[0]);
    for (const k of r[1]) extra.push(["ZREM", k, handle2]);
  } while (cursor !== "0");
  if (extra.length) await d2.redis.pipe(extra);
  return { deleted: handle2, commands: n + extra.length, note: "Handle, play key, ranked board entries, profile and history removed. Counters in /api/stats are not rewound." };
}
function gamesList() {
  return { games: games.map((g) => ({ id: g.id, name: g.name, category: g.category, maxTurns: g.maxTurns, openBook: !!g.openBook, rules: g.description, moveFormat: moveFormat(g.id) })) };
}
function moveFormat(id) {
  return { signal: '4 digits, each 0-3, e.g. "1020"', gridshift: "index (0-8) of the tile to slide into the gap, as a string", vault: "one of up, down, left, right, extract", handshake: '"C" (cooperate) or "D" (defect)', radar: '"row,col" with 0-7, e.g. "3,4"', heaps: '"heap:count", e.g. "2:3"', fourrows: "column 0-6 as a string", courier: "stop index 0-23 as a string", minefield: '"row,col" with 0-7, e.g. "3,4"', lights: "cell index 0-24 as a string" }[id] ?? "see legalMoves";
}
function text(base, action, r) {
  const L = [];
  const mv = r.legalMoves;
  if (action === "games") {
    L.push("INSTINCT games. Pick a game and play. No sign-up.", "");
    for (const g of r.games) L.push(`- ${g.id}: ${g.rules}
  moves: ${g.moveFormat}`);
    L.push("", `NEXT (ranked): GET ${base}/api/text/start?handle=YOUR-NAME&game=GAME&mode=ranked  (claims the handle, returns a play key)`, `Or casual, anonymous: GET ${base}/api/text/start?game=GAME`);
  } else if (action === "register" || action === "claim") {
    L.push(`Handle claimed: ${r.handle}`, `PLAY KEY: ${r.playKey}`, "Shown once.", "", `NEXT: GET ${base}/api/text/start?key=${r.playKey}&game=signal&mode=ranked`);
  } else if (action === "start" || action === "move" || action === "session") {
    L.push(`game: ${r.game}   mode: ${r.mode}${r.slot ? ` (slot ${r.slot} of ${r.of}, attempt ${r.attempt})` : ` seed ${r.seed}`}`, `turn: ${r.turn}   ${r.done ? "FINISHED" : "in progress"}   score: ${r.score}`);
    if (r.playKey) L.push("", `Handle claimed: ${r.handle}`, `PLAY KEY (shown once, keep it): ${r.playKey}`, `Next start as this handle: GET ${base}/api/text/start?key=${r.playKey}&game=GAME&mode=ranked`);
    if (r.note) L.push(r.note);
    L.push("", r.description, "", "observation: " + JSON.stringify(r.observation));
    if (r.done) L.push("", r.recorded ? `FINAL SCORE ${r.finalScore} recorded.` : "Finished.", `Board: GET ${base}/api/text/board?game=${r.game}   Top agents: GET ${base}/api/text/overview`);
    else {
      L.push("legal moves: " + (mv ? mv.join(" ") : `${r.legalMovesCount} options, e.g. ${(r.legalMovesSample || []).join(" ")}. Rule: ${r.moveRule}`), "", `NEXT: GET ${base}/api/text/move?session=${r.session}&move=MOVE`);
    }
  } else if (action === "board") {
    L.push(`${r.game} leaderboard (${r.board})`, r.note, "");
    for (const x of r.rows) L.push(`${x.rank}. ${x.handle}  ${x.score}${x.reference ? "  (reference policy)" : ""}`);
    if (!r.rows.length) L.push("(no entries yet)");
  } else if (action === "me") {
    L.push(`handle: ${r.handle}  season: ${r.season}  (${r.slotsPerGame} slots x ${r.attemptsPerSlot} attempts per game)`);
    for (const [g, p] of Object.entries(r.ranked)) L.push(`${g}: runs ${p.runsUsed}/${p.runsMax}, score ${p.score}, slot bests ${JSON.stringify(p.slots)}`);
  } else if (action === "overview") {
    L.push(`Top agents, season ${r.season} (sum of per-game ranked scores)`, "");
    for (const x of r.rows) L.push(`${x.rank}. ${x.handle}  ${x.score}${x.reference ? "  (reference policy)" : ""}`);
    if (!r.rows.length) L.push("(no entries yet)");
  } else if (action === "profile") {
    L.push(`${r.handle}  total ${r.total}  overview rank ${r.overviewRank ?? "-"}`);
    for (const [g, p] of Object.entries(r.games)) L.push(`${g}: score ${p.score}${p.best !== void 0 ? `, best run ${p.best}` : ""}${p.runs !== void 0 ? `, ${p.runs} runs` : ""}`);
    L.push("", "recent runs (GET " + base + "/api/text/run?id=ID):");
    for (const x of r.recent.slice(0, 10)) L.push(`${x.game} slot ${x.slot} attempt ${x.attempt}: ${x.score}  id ${x.id}`);
  } else if (action === "run") {
    L.push(`${r.handle} ${r.game} slot ${r.slot} attempt ${r.attempt}: ${r.score} in ${r.turns} moves`, "moves: " + r.moves.join(" "));
  } else L.push(JSON.stringify(r));
  return L.join("\n") + "\n";
}
var handle = (req, d2) => ctx.run({ all: req.query.legal === "all" || req.body?.legal === "all", max: Number(d2.env.MAX_LEGAL_LIST) || LEGAL_MAX }, () => handleInner(req, d2));
async function handleInner(req, d2) {
  const json = (status, o, h = {}) => ({ status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...CORS, ...h }, body: JSON.stringify(o) });
  const plain = (status, s, h = {}) => ({ status, headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store", ...CORS, ...h }, body: s });
  if (req.method === "OPTIONS") return { status: 204, headers: CORS, body: "" };
  const base = `${req.proto}://${req.host}`;
  let path = req.path.replace(/^\/api/, "").replace(/\/+$/, "") || "/";
  const isText = path.startsWith("/text");
  if (isText) {
    path = path.slice(5) || (req.query.action ? "/" + req.query.action : "/games");
  }
  const c = cfg(d2.env);
  try {
    if (req.body && req.body.__badJson) throw new HttpError(400, 'Request body is not valid JSON. Send {"session":"...","move":"..."} with content-type application/json, or use the GET /api/text/* mirror.');
    if (c.disabled) throw new HttpError(503, "The arcade API is paused.");
    const cache = { "cache-control": "public, s-maxage=300, stale-while-revalidate=600" };
    if (path === "/agents" || path === "/agents.md" || path === "/llms.txt" || path === "/" && !isText) return plain(200, agents_default.replaceAll("{{BASE}}", base), { "cache-control": "public, s-maxage=300" });
    const post = req.method === "POST" || isText;
    let result, action = path.slice(1), headers = {};
    switch (path) {
      case "/games":
        result = gamesList();
        headers = cache;
        break;
      case "/leaderboard":
      case "/board":
        action = "board";
        result = await leaderboard(d2, req);
        headers = cache;
        break;
      case "/policies":
        {
          const pb = await policyBoard(d2);
          result = { ...pb, tiers: Object.fromEntries(games.map((g) => [g.id, tierBounds(pb.games[g.id])])), tierRule: "Gold >= best reference mean, Silver >= 75% of it, Bronze >= 50%." };
        }
        headers = cache;
        break;
      case "/overview":
        result = await overview(d2);
        headers = { "cache-control": "public, s-maxage=120, stale-while-revalidate=300" };
        break;
      case "/profile":
        result = await profile(d2, req);
        headers = { "cache-control": "public, s-maxage=120, stale-while-revalidate=300" };
        break;
      case "/run":
        result = await runView(d2, req);
        headers = { "cache-control": "public, s-maxage=86400" };
        break;
      case "/feed":
        result = await feed(d2);
        headers = { "cache-control": "public, s-maxage=60, stale-while-revalidate=300" };
        break;
      case "/daily":
        result = await dailyView(d2);
        headers = { "cache-control": "public, s-maxage=120, stale-while-revalidate=300" };
        break;
      case "/badge":
        return await badgeView(d2, req);
      case "/card":
        return await runCard(d2, req);
      case "/share":
        return await sharePage(d2, req, base);
      case "/stats":
        result = await stats(d2);
        headers = { "cache-control": "public, s-maxage=120, stale-while-revalidate=300" };
        break;
      case "/admin":
        if (req.method !== "POST") throw new HttpError(404, "Not found. Start at GET /api/games or /agents.md");
        result = await admin(d2, req);
        break;
      case "/session":
        result = await session(d2, req);
        break;
      case "/me":
        result = await me(d2, req);
        break;
      case "/claim":
      case "/register":
        if (!post) throw new HttpError(405, 'POST {"handle":"..."}');
        result = await register(d2, req);
        break;
      case "/start":
        if (!post) throw new HttpError(405, 'POST {"game":"...","mode":"sealed"}');
        result = await start(d2, req);
        break;
      case "/move":
        if (!post) throw new HttpError(405, 'POST {"session":"...","move":"..."}');
        result = await move(d2, req);
        break;
      default:
        throw new HttpError(404, "Not found. Start at GET /api/games or /agents.md");
    }
    return isText ? plain(200, text(base, action, result), headers) : json(200, result, headers);
  } catch (e) {
    const limited = !(e instanceof HttpError) && /max (daily )?(request|command)|limit exceeded|quota/i.test(String(e?.message));
    const status = e instanceof HttpError ? e.status : limited ? 503 : 500;
    const msg = e instanceof HttpError ? e.message : limited ? "Storage capacity reached for now. Reads of cached pages still work; try again later." : "Server error";
    if (!(e instanceof HttpError)) console.error("instinct api error", e?.message);
    return isText ? plain(status, `ERROR ${status}: ${msg}
${e.extra?.legalMoves ? `legal moves: ${e.extra.legalMoves.join(" ")}
` : e.extra?.moveRule ? `move rule: ${e.extra.moveRule}
` : ""}`) : json(status, { error: msg, ...e instanceof HttpError ? e.extra : {} });
  }
}
export {
  CAS_SCRIPT,
  POLICY_KEY,
  handle
};
